### PR TITLE
Fix broken links for "edit this page" per #1358

### PR DESCRIPTION
**Pull request by willium**
Quick fix :)

### CODE REVIEW

**Comment by domoritz** [comment]
Can you explain what was happening?

**Comment by willium** [comment]
@domoritz click 'edit this page' on https://vega.github.io/vega-lite/tutorials/explore.html

**Comment by domoritz** [comment]
I want to know why we have this weird bower modules thing in the path though. I see the problem but don't understand it.

**Comment by willium** [comment]
Yeah, my bad. Fixed it proper. (bower's vega-lite needed to be ignored within Jekyll).

**Comment by domoritz** [comment]
I like that more.

**Pull request merged**
