### PR TITLE
fix: don't remove value refs from legend config since it shouldn't have them in the first place

### PR DESCRIPTION
**Pull request by domoritz**
Needs https://github.com/vega/vega/pull/2499
Fixes https://github.com/vega/vega-lite/issues/6240

### CODE REVIEW

**Comment by kanitw** [comment]
Sounds reasonable, but it's failing tests.

**Comment by domoritz** [comment]
Yes, because it needs vega/vega#2499 :-P

**Comment by kanitw** [comment]
still failinng

**Comment by domoritz** [comment]
After rebasing, tests pass now.

**Pull request merged**
