### PR TITLE
fix: always use sort min even if chart is stacked

### PR DESCRIPTION
**Pull request by domoritz**
Fixes https://github.com/vega/vega-lite/issues/6064

### CODE REVIEW

**Comment by kanitw** [comment]
What if the sort field is quantitative? Sum is probably better?

**Comment by domoritz** [comment]
I’m not sure it is better, actually. We use min everywhere else so using sum all of a sudden could come as a surprise. I’d vote for consistency over smartness here.

**Comment by kanitw** [comment]
I think it should be min if the sort field is a groupby, but sum if the sort field is not a groupby?

**Comment by domoritz** [comment]
That would also work but I am not yet convinced that `min` isn't easier and is right for almost all cases. Note that if you sort by the stacked field, we don't have to do any aggregation.

**Comment by kanitw** [comment]
> Note that if you sort by the stacked field, we don't have to do any aggregation.

When you sort by a stacked quantitative field, you have to sum them.

**Comment by domoritz** [comment]
If we sort by the stacked field, we don't need any aggregation since we group by the color already, no?

**Comment by kanitw** [comment]
> If we sort by the stacked field, we don't need any aggregation since we group by the color already, no?

The sorted value should be summed across color groups.  That's not the result of the original aggregation.

**Comment by domoritz** [comment]
Oh right, then yes, we want to sum up the data. Let's revise this pull request.

**Comment by domoritz** [comment]
Okay, so the issue is more nuanced

Should use min

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"val": 1, "val2": 1.1, "label": "A"},
      {"val": 2, "val2": 1.8, "label": "B"},
      {"val": 3, "val2": 3.2, "label": "A"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "val2", "type": "quantitative"},
    "y": {"field": "val", "type": "ordinal", "sort": {"field": "label"}},
    "color": {"field": "label", "type": "nominal"}
  }
}
```


Should use sum

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"val": 1, "val2": 1.1, "label": "A"},
      {"val": 2, "val2": 1.8, "label": "B"},
      {"val": 3, "val2": 3.2, "label": "A"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "val2", "type": "quantitative"},
    "y": {"field": "val", "type": "ordinal", "sort": {"field": "val2"}},
    "color": {"field": "label", "type": "nominal"}
  }
}
```

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {
    "values": [
      {"val": 1, "val2": 1.1, "label": "A"},
      {"val": 2, "val2": 1.8, "label": "B"},
      {"val": 3, "val2": 3.2, "label": "A"}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "val2", "type": "quantitative"},
    "y": {"field": "val", "type": "ordinal", "sort": "x"},
    "color": {"field": "label", "type": "nominal"}
  }
}
```

**Comment by domoritz** [comment]
I'll send a new pull request.

**Pull request closed without merging**
