### PR TITLE
Config strip

### PR DESCRIPTION
**Pull request by kanitw**
Fix https://github.com/vega/vega-lite/issues/1995 and https://github.com/vega/vega-embed/issues/27

This requires follow-up changes in vega-embed and vega-editor.

### CODE REVIEW

**Comment by kanitw** [comment]
@domoritz  besides #1995, there was another issue that you're asking for this change, but I couldn't find it.

**Comment by kanitw** [comment]
NVM found it https://github.com/vega/vega-embed/issues/27

**Comment by domoritz** [comment]
Let's make sure that we have PRs for vega-embed and vega editor before merging this.

**Comment by kanitw** [comment]
@domoritz  I don't have time to do that -- feel free to go ahead and do it.  But even if we don't have that thing should still work, Vega will just dumbly having config twice.

**Comment by kanitw** [comment]
@domoritz  Since this doesn't really break vg-embed and editor, I'd say we better merge this and file issues for editor/embed to avoid conflicts. (I already have to rebase and resolve conflicts once for no good reason.)

**Comment by kanitw** [comment]
https://github.com/vega/vega-embed/issues/28
https://github.com/vega/vega-editor/issues/109

**Comment by domoritz** [comment]
I think it would be nice to add a basic unit test but looks like we have test covering the code in some way at least.

**Pull request merged**
