### PR TITLE
fix: updated types for projection fit

### LINKED ISSUE #7448: [Schema] Allow feature collections to be used with projection fit and add documentation
[Projection fit](https://vega.github.io/vega-lite/docs/projection.html#projection-properties) is currently missing documentation details, but does work. It is presumably designed to work as [Vega's fit](https://vega.github.io/vega/docs/projections/#properties) in taking either a feature collection object or an array of features. Both of these work in practice, but the VegaLite Schema rejects the feature collection object version.

Here's minimal reproducible example that works but is rejected by the VL schema.

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
 
  "data": {
    "url": "https://cdn.jsdelivr.net/npm/vega-datasets@2.2/data/world-110m.json",
    "format": {"type": "topojson", "feature": "land"}
  },
  "projection": {
    "fit": {
      "features": [
        {
          "geometry": {
            "coordinates": [[[-3, 52], [4, 52], [4, 45], [-3, 45], [-3, 52]]],
            "type": "Polygon"
          },
          "type": "Feature"
        },
        {
          "geometry": {
            "coordinates": [[[-3, 59], [4, 59], [4, 52], [-3, 52], [-3, 59]]],
            "type": "Polygon"
          },
          "type": "Feature"
        }
      ],
      "type": "FeatureCollection"
    }
  },
  "mark": {"type": "geoshape", "clip": true}
}
```

Can the schema be updated to accept both Feature Collection objects and feature arrays? And can the API documentation detail be added (which can simply match the Vega version)?

### PR DESCRIPTION
**Pull request by astrophie**
Updated the TypeScript definition for the Projection interface to allow both Feature Collection objects and Feature arrays for the fit property.
Added API documentation in comments.

Fixes #7448

### CODE REVIEW

**Review by domoritz — CHANGES_REQUESTED** [review]
Great start. I ran `yarn schema` to update the schema and pushed it. 

However, this changeset does not yet fix the issue that the valid feature collection is not accepted.  Please update the types (maybe we need to change types in Vega, not sure) and add an example so we test compatibility. 

Screenshot 2024-02-15 at 20 38 38

**Comment by domoritz** [comment]
@astrophie can you wrap up this pull request?

**Comment by domoritz** [comment]
Why did you close this?

**Comment by astrophie** [comment]
> Why did you close this?

I wasn't able to get the example added in the src folder after a few attempts. I didn't think it was super necessary as the schema type fix from before seems to fix the bug, and that was already merged?

**Comment by domoritz** [comment]
Oh I missed that. What's the pull request or commit that fixed it?

**Pull request closed without merging**
