### PR TITLE
Run tests on node 11

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
Can you give more context i.e., explain the rationale behind the change?

**Comment by kanitw** [comment]
But didn't node only have long-term-support (LTS) for even number versions?  

If so, shouldn't the main test be 10 until 12 is out?

**Comment by domoritz** [comment]
Merge @kanitw?

**Comment by kanitw** [comment]
I don't have strong opinion here. So if you strongly think we should do this, go ahead.

**Pull request merged**
