### PR TITLE
add support to axis' time format in composite mark (use Vega 5.1's formatType)

### PR DESCRIPTION
**Pull request by chanwutk**

### CODE REVIEW

**Comment by domoritz** [comment]
Tests are failing.

**Comment by kanitw** [comment]
Note: timeFormat for Vega doesn't really support quarter

**Comment by domoritz** [comment]
> Note: timeFormat for Vega doesn't really support quarter

:-(

@jheer do you think it's worth supporting it in Vega? If yes, we probably want to do it in D3, right?

**Comment by jheer** [comment]
Yes, we use d3-time-format directly so that would be the ideal place to do it.

**Comment by kanitw** [comment]
FYI, I created https://github.com/d3/d3-time-format/issues/56 and Mike has some thoughts about deprecating the library.

**Comment by jheer** [comment]
Thanks @kanitw! Maybe Vega 6 can move to browser built-in’s for date formatting and parsing. It would be wonderful to have international locales out-of-the-box!!

In the meantime, however, we might consider forking d3-time-format if a PR for quarter suppport will not be accepted?

**Comment by jheer** [comment]
FYI it also looks like Date.toLocaleString does not support quarters... ☹️

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString

**Comment by domoritz** [comment]
@chanwutk What's left here?

**Comment by chanwutk** [comment]
I am trying to use pass format and formatType from Vega-Lite to Vega directly. But since Vega hasn't supported quarter yet, aren't we going to use the old implementation (format time with `encode`) #4190 ?

**Comment by domoritz** [comment]
Yes

**Comment by kanitw** [comment]
I guess we don't need this anymore.

**Pull request closed without merging**
