### PR TITLE
Add customized scale, translate support for projections.

### LINKED ISSUE #3942: Support projection property center and scale
In the Vega-Lite documentation it says projection has several properties (https://vega.github.io/vega-lite/docs/projection.html).  However in the spec below I can change "center": [0,0] to whatever, there is no resulting shift. Rotate and clipExtent work. And it's frustrating anyway that the normal D3/Vega projection.scale is not available. How can I zoom in to a part of the world now...?

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.1.json",
  "width": 500,
  "height": 300,
  "data": {
    "url": "data/world-110m.json",
    "format": {
      "type": "topojson",
      "feature": "countries"
    }
  },
  "projection": {
    "type": "equirectangular",
    "clipExtent": [[0,0],[500,300]],
    "rotate": [0,0,0],
    "center": [0,0]
  },
  "mark": {
    "type": "geoshape",
    "stroke": "white",
    "fill": "#ccc"
  }
}
```

### PR DESCRIPTION
**Pull request by jheer**
Changes:
- Adds `scale` and `translate` properties to the Projection interface.
- Add clipping to projected marks if either `scale` or `translate` is defined.
- Disable auto-`fit` of projection parameters if either `scale` or `translate` is defined.
- Fix bug in `scaleClip` (src/compile/mark.ts): return `undefined`, not `false`.
- Update tests, documentation.

Fix #3942.

### CODE REVIEW

**Comment by domoritz** [comment]
Does this fix https://github.com/vega/vega-lite/issues/3942?

**Comment by jheer** [comment]
@domoritz Yes, I updated the PR comment to close out the issue once merged.

**Comment by jheer** [comment]
I realized I made an oversight, in that unnecessary GeoJSON transforms were still being generated and then never referenced. The latest commits fix that and introduce related test/example. Once CI tests complete successfully this should hopefully be ready to merge.

**Comment by domoritz** [comment]
Can we use a type guard for isFit?

**Comment by jheer** [comment]
Being a TypeScript novice, I do not know what you mean by that.

**Comment by domoritz** [comment]
This was a comment for @willium since he merged and I didn't have time to look into this patch, yet.

**Comment by willium** [comment]
I didn't think the type guard was needed. is this part of our move towards parsing types for the api?

**Pull request merged**
