### PR TITLE
feat: update to Vega 5.11, support domain/grid/tickCap

### PR DESCRIPTION
**Pull request by kanitw**
Merge ~~#6446~~ #6426 first

### CODE REVIEW

**Comment by kanitw** [comment]
NVM, this seems redundant with #6391

**Comment by kanitw** [comment]
Actually we haven't added the proper docs in #6391

**Comment by domoritz** [comment]
I only added what was needed to make my builds pass.

**Comment by domoritz** [comment]
Let's merge this after https://github.com/vega/vega-lite/pull/6400 to reduce conflicts.

**Pull request merged**
