### PR TITLE
DOC: Update interactive_panzoom_vconcat_shared example

### PR DESCRIPTION
**Pull request by jakevdp**
Change the shared scale from ``y`` to ``x``, which makes the example better match the documentation text (see https://vega.github.io/vega-lite/docs/bind.html#scale-binding)

### CODE REVIEW

**Comment by jakevdp** [comment]
I think that should do it... let's see what Travis says.

**Comment by jakevdp** [comment]
BTW, I found that in a fresh clone I needed to first run ``yarn build:examples`` before I could run the command to build a single example.

**Comment by arvind** [comment]
Thanks @jakevdp!

**Comment by domoritz** [comment]
It's sufficient to run `yarn build` (`yarn build:examples` takes a few minutes unless you have a beefy machine). I would love to have a more robust build system but it's tricky to get right.

**Pull request merged**
