### PR TITLE
Fix all docs url to use absolute url

### PR DESCRIPTION
**Pull request by kanitw**
cc: @jakevdp

### CODE REVIEW

**Comment by kanitw** [comment]
@domoritz  -- I start wondering if we should do this in the rename script so that we won't forget about it anymore and make the JS code simpler.

**Comment by domoritz** [comment]
How do we automate this?

**Comment by kanitw** [comment]
Replace `\]\(([^/.]*).html` with `](https://vega.github.io/vega-lite/docs/$1.html`

**Comment by domoritz** [comment]
Although I like to have all URLs absolute as it also means our typescript typings have helpful links. I think we should enforce absolute URLs instead.

**Comment by kanitw** [comment]
Ok i add check script instead.

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
