### PR TITLE
Docs consistency

### PR DESCRIPTION
**Pull request by domoritz**
Make docs more consistent by removing selection- preix and also grouping docs in folders.

### CODE REVIEW

**Comment by kanitw** [comment]
One small problem with this renaming scheme is that selection project does not even have `project` name so I kinda feel like it's a bit confusing?

**Comment by domoritz** [comment]
Yeah, there is no project keywords but that's a separate issue and I don't think it's a big issue.

**Comment by kanitw** [comment]
Ok sure. There are a lot of conflicts for some reason though.

**Comment by domoritz** [comment]
Fixed

**Pull request merged**
