### PR TITLE
feat: upgrade Vega to 5.20

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Review by chanwutk — APPROVED** [review]

**Comment by domoritz** [comment]
@chanwutk it looks like this update broke some example images

Screen Shot 2021-04-07 at 21 55 28

**Comment by chanwutk** [comment]
Hi, sorry I did not look at the output picture diff.
It seems like there errors when using vega-cli.
Here is the screenshot of CI from commit 9387aa7 above.
Screenshot from 2021-04-07 22-47-05

**Comment by domoritz** [comment]
I think the issue is https://github.com/vega/vega-lite/pull/7225. I'm fixing it in https://github.com/vega/vega-lite/pull/7368

**Comment by chanwutk** [comment]
I see. Thank you!

**Pull request merged**
