### PR TITLE
Normalized Stacked Bar Chart

### PR DESCRIPTION
**Pull request by ayush29feb**
Added the normalize property for the stacked graphs. Test is missing.

### CODE REVIEW

**Comment by domoritz** [comment]
Is this commit ready for review? If not, can you add a [WIP] label to the title?

**Comment by domoritz** [comment]
Does this fix https://github.com/vega/vega-lite/issues/982?

**Comment by ayush29feb** [comment]
I am not sure about the #982. The 'offset: normalize' works and is ready for review. I still need to write the testing code.

**Comment by kanitw** [comment]
A few comments: 
- This fixes #402, but does not fix #982.  The PR name should be  “Normalized Stacked Bar Chart”.  Please also mention #402 in the description.  
- Looks like this PR also have some commits from another PR.  Unless this depends on another PR, better fork from master and include only relevant commits in the same PR.  (In this case, you might want to do this correctly and re-open another PR.)

**Comment by ayush29feb** [comment]
1. Should I fix #982 before I submit this pull request for review?
2. Yeah, I am sorry about that, I didn't realize the checked it out from the wrong branch. I will fix that

**Comment by kanitw** [comment]
1.  #982 is irrelevant to this.  @domoritz only mentioned it because the old title makes him thought you mean #982.   

2.  No big deal!  We sometimes made this kind of mistake too -- You can check out master, create a new branch, cherry pick relevant commits from this branch and submit a new PR. :)

**Comment by kanitw** [comment]
Correction: irrelevant -- not very relevant.

**Pull request closed without merging**
