### PR TITLE
Feat: allow for `normalizedNumberFormat` for `stack: "normalize"` tooltips

### PR DESCRIPTION
**Pull request by lsh**
This PR addresses #8300. As mentioned in the referenced issue, the spelling of the `normalizedNumberFormat` field may be subject to change (per feedback of @domoritz @jheer).

**Important**: The `normalizedNumberFormat` should only be applied to tooltips that are `stack: "normalize"`. Furthermore, this PR intentionally does not implement the `normalizedNumberFormat[Type]` encoding for `src/compile/legend/encode.ts` because @kanitw and I could not think of a non positional situation where `stack` is used.

### CODE REVIEW

**Comment by lsh** [comment]
Note: this PR will either need to rebase if #8302 is merged first, or vice versa.

**Comment by kanitw** [comment]
> @kanitw and I could not think of a non positional situation where `stack` is used.

Looking at the code more, it's also worth noting that `stack?:` is defined in `PositionBaseMixins` and thus won't be used by non-position encoding.

**Review by kanitw — COMMENTED** [review]
Add some tests so codecov won't complain?

**Comment by lsh** [comment]
Closing in favor of #8307

**Pull request closed without merging**
