### PR TITLE
[Enhancement] Enable legend for strokeWidth

### PR DESCRIPTION
**Pull request by kanitw**
Part of https://github.com/vega/vega-lite/issues/4982

### CODE REVIEW

**Comment by kanitw** [comment]
image

**Comment by domoritz** [comment]
I fixed the tests for you.

**Comment by kobben** [comment]
Great, thanks. 
Sorry for being a bit ignorant about how Git works, but when can I expect this to be in the "published" version i.e. working in the online editor? Or alternatively, how do I get a local version of thjs "branch" (or is it now the "master")...?

**Comment by domoritz** [comment]
This is now in Master. We make releases every few weeks and then publish it in the editor as well. Of you want to use it now, you have to clone the editor and Vega-Lite and link them as described in the contributing guidelines.

If you just use npm, you can also depend on the master version from.github in your project.

**Pull request merged**
