### PR TITLE
fix table style to target on page content

### PR DESCRIPTION
**Pull request by sirahd**

### CODE REVIEW

**Comment by domoritz** [comment]
Hmm, what do you think about adding https://developer.mozilla.org/en-US/docs/Web/CSS/isolation to the tooltip css? I think may people override tables.

Also, why do we use tables in the tooltips? Can we avoid that?

**Comment by domoritz** [comment]
As explained above, I think a table is the wrong approach for tooltips. https://github.com/vega/vega-tooltip/issues/115

**Comment by kanitw** [comment]
I disagree.  They are semantically table.

**Comment by kanitw** [comment]
Plus, while people may override table, doing so is a bad practice anyway so I'm gonna merge this.

**Comment by kanitw** [comment]
Btw, I don't think the `isolation` property is relevant here.

**Comment by domoritz** [comment]
Hmm, I thought is isolates case scopes but I've never used it.

**Pull request merged**
