### PR TITLE
Fallback legend properties to LegendConfig props

### LINKED ISSUE #1310: Cannot set legend label properties
Legend title properties work, but legend label properties do not.

```json
{
  "data": { "url": "data/population.json"},
  "transform": {
    "filter": "datum.year == 2000",
    "calculate": [{"field": "gender", "expr": "datum.sex == 2 ? \"Female\" : \"Male\""}]
  },
  "mark": "bar",
  "encoding": {
    "column": {
      "field": "age", "type": "ordinal",
      "scale": {"padding": 4},
      "axis": {"orient": "bottom", "axisWidth": 1, "offset": -8}
    },
    "y": {
      "aggregate": "sum", "field": "people", "type": "quantitative",
      "axis": {"title": "population", "grid": false}
    },
    "x": {
      "field": "gender", "type": "nominal",
      "scale": {"bandSize": 6},
      "axis": false
    },
    "color": {
      "field": "gender", "type": "nominal",
      "scale": {"range": ["#EA98D2", "#659CCA"]}
    }
  },
  "config": {
    "legend": {
     "properties": {
       "title": {
         "fill": {"value": "green"},
         "fontSize": {"value": 30}
       },
       "labels": {
         "fill": {"value": "red"},
         "fontSize": {"value": 30}
       }
     }
    }
  }
}
```

unknown

### PR DESCRIPTION
**Pull request by mprudhom**
Fixes #1310

### CODE REVIEW

**Comment by domoritz** [comment]
I think this should use extend, right @kanitw?

**Comment by kanitw** [comment]
I think each of the functions already take `props[group]` as input, so we don't really need this.

**Comment by kanitw** [comment]
Thanks for submitting though.   @mprudhom

**Comment by mprudhom** [comment]
I don't quite understand. Do you mean that there is a better solution to issue #1310?

**Comment by kanitw** [comment]
The issue is already accidently fixed by a recent change.

**Pull request closed without merging**
