### PR TITLE
Update Codecov command to match latest tutorial

### PR DESCRIPTION
**Pull request by kanitw**
https://github.com/istanbuljs/nyc#integrating-with-codecov

### CODE REVIEW

**Comment by kanitw** [comment]
Hmm ... it still doesn't run codecov.

**Comment by kanitw** [comment]
@arvind Actually it does not.  I'm just trying randomly to see what causes codecov to break...

**Comment by arvind** [comment]
I feel you!

**Comment by kanitw** [comment]
Doesn't work yet ...

**Pull request closed without merging**
