### PR TITLE
docs: update valid image path

### LINKED ISSUE #9151: Missing tooltip images in docs
At https://vega.github.io/vega-lite/docs/tooltip.html#tooltip-image the image doesn't show up. 

Screenshot 2023-10-23 at 11 47 04

### PR DESCRIPTION
**Pull request by ChiaLingWeng**
this is a follow up to #9171 and will close #9151.
since the original pull request is a little messy and the workflow failed thus open a new one here, 
for this issue, the most graceful solution I think is to add a symbolic link that points to the valid data folder.

image

### CODE REVIEW

**Comment by domoritz** [comment]
Hmm, https://vega.github.io/vega-lite/docs/image.html#examples works but https://vega.github.io/vega-lite/docs/tooltip.html#tooltip-image does not because the base url doesn't seem to be set correctly for the tooltip.

**Comment by domoritz** [comment]
I think the real issue here is that the tooltip plugin doesn't use the baseurl from the loader.

**Comment by domoritz** [comment]
I think the best fix is to pass the baseurl through to tooltips. Done in https://github.com/vega/vega-embed/pull/1286

**Comment by ChiaLingWeng** [comment]
Good to know where is the issue from, thanks!

**Comment by domoritz** [comment]
Thank you for filing the bug and looking into fixing it. Seeing your fixes helped me pinpoint the bug much faster.

**Pull request closed without merging**
