### PR TITLE
Merge Axis

### PR DESCRIPTION
**Pull request by kanitw**
Part of #2473 

Merge Axis

- Output Vega axis now shows explicitly specified axis first
- Now gridScale is always produced -- See layered falkansee
- Now title is merged for different fields (with comma)

### CODE REVIEW

**Comment by kanitw** [comment]
@domoritz @arvind -- Can one of you review this to avoid merge conflicts?

**Comment by domoritz** [comment]
Typo, it's "Falkensee". 

Also, on it.

**Comment by domoritz** [comment]
Setting an explicit title in the falkensee example doesn't seem to work

```json
{
      "mark": "line",
      "encoding": {
        "x": {
          "field": "year",
          "type": "temporal",
          "timeUnit": "year",
          "title": "Year"
        },
        "y": {"field": "population", "type": "quantitative"},
        "color": {"value": "#333"}
      }
    }
```

**Comment by domoritz** [comment]
I can't set the title on the x2 axis. Not sure whether that should be suported or not. 

```
"x2": {
          "field": "end",
          "type": "temporal",
          "timeUnit": "year",
          "axis": {
            "title": "Foo"
          }
        },
```

**Comment by kanitw** [comment]
> Typo, it's "Falkensee".

Sorry, I shouldn't have misspell it since it's easier than my last name :p 

> I can't set the title on the x2 axis. Not sure whether that should be suported or not.

Intentionally not supported.  (Didn't you get JSON schema warning for it? -- If not, then something is wrong.)

**Pull request merged**
