### PR TITLE
Add heatmap example. #1342

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by aishfenton** [comment]
Rather than using `square` would it be better to use `bar`? Since the result it gives looks much better. Although marking it as "bar" does seem confusing, but at least it looks like a heat map :)

**Comment by domoritz** [comment]
@aishfenton Ups. I pushed the wrong version. Thanks for paying attention!

**Comment by kanitw** [comment]
@domoritz  Honestly let's not add this.   It's a hack, not a well principle design. 
Our principled design is to add `rect` mark.

**Comment by domoritz** [comment]
We should add the spec and fix it later. We will change to rect or tile before the 2.0 release.

**Comment by kanitw** [comment]
Have another WIP branch that will handle this correctly.

**Pull request closed without merging**
