### PR TITLE
Bin

### LINKED ISSUE #816: Add missing bin parameter
We only have `maxbins` — need to add `min`, `max`, `step`, `steps`, `minstep`, `div`

### PR DESCRIPTION
**Pull request by kanitw**
- fixes #816 -- add missing bin parameter
- [x] Auto maxbins
- [x] docs
- [x] unit-tests

### CODE REVIEW

**Comment by kanitw** [comment]
Ready for review — note that I’m hiding `scatter_binned` from example as it’s broken due to a vega bug:  https://github.com/vega/vega/issues/468.

**Comment by domoritz** [comment]
> Ready for review — note that I’m hiding scatter_binned from example as it’s broken due to a vega bug: vega/vega#468.

Since datalib will fix this soon, maybe not hide it for now.

**Comment by jheer** [comment]
datalib 1.5.7 is released, so hopefully the problem is now resolved.

**Comment by kanitw** [comment]
Let’s undo hide in the examples branch as the list files has been changed to a json file.

**Comment by domoritz** [comment]
> Let’s undo hide in the examples branch as the list files has been changed to a json file.

Referring to https://github.com/vega/vega-lite/pull/848

**Comment by kanitw** [comment]
Actually, datalib 1.5.7 would fix that but since Vega embed datalib in its compile, this won't be resolved until Vega releases a newer version.

**Pull request merged**
