### PR TITLE
Added data.world chart builder to applications documentation

### PR DESCRIPTION
**Pull request by jonloyens**
Adding application documentation links to data.world Chart Builder application/open source project per request from @domoritz in the Slack channel.

### CODE REVIEW

**Comment by jonloyens** [comment]
Sure. Was trying to add some consistency with the bullets.  I can go
through and add more of those if you want (to make it even more consistent)
or is there special connotation to those bullets that I'm not aware of?

**Comment by jonloyens** [comment]
Ahh... those are featured. I get it.  Will remove.

**Comment by jonloyens** [comment]
Fixed comments. Unsure of the changes in docs_toc.md and versions.yml since they seemed to be autogenerated by the build tool (I never manually touched those files)

**Comment by domoritz** [comment]
Thanks

**Pull request merged**
