### PR TITLE
feat: add vl2pdf, test the cli, support windows

### PR DESCRIPTION
**Pull request by domoritz**
Fixes https://github.com/vega/vega-lite/issues/4727

### CODE REVIEW

**Comment by domoritz** [comment]
@stenzengel do you know why windows is failing? How do I test stdin?

**Comment by stenzengel** [comment]
For my tests I used `vl2vg < test.json` as in the original description of #4727. (After this worked without error, also my original use case with `asciidoctor-diagram` worked). Another possibility should be using `type` instead of `cat`.

**Comment by domoritz** [comment]
That still doesn't seem to work @stenzengel.

Screen Shot 2020-03-08 at 18 13 03

**Comment by domoritz** [comment]
Nothing seems to work. Note that github actions use powershell. Can you help me get this test working @stenzengel?

**Comment by stenzengel** [comment]
@domoritz Yes, the problem is that GitHub Actions use Powershell. I had the same problem (`The '<' operator is reserved for future use`) after switching to Powershell. I have [found](https://stackoverflow.com/questions/2148746/the-operator-is-reserved-for-future-use) the following workaround, which worked for me:
```
Get-Content test.vl.json | vl2vg.cmd > test.vg.json
```
Please note, that I also had to add the ".cmd" extension to "vl2vg".

Hope that helps.

**Pull request merged**
