### PR TITLE
docs: document that encoding a field as a tooltip groups by the field

### PR DESCRIPTION
**Pull request by domoritz**
Fixes https://github.com/vega/vega-lite/issues/6920

### CODE REVIEW

**Comment by kanitw** [comment]
Wondering if this comment really make sense for only tooltip, given adding an unaggregated field to *any* encoding?

**Comment by domoritz** [comment]
I generally agree. People seem to struggle a lot more for tooltips than other encodings, though.

**Comment by domoritz** [comment]
Should we still merge this?

**Review by donghaoren — APPROVED** [review]
An example might help here? I had to read the sentence a few times to comprehend it...

**Comment by domoritz** [comment]
I rewrote the text and added examples. What do you think now @donghaoren?

**Pull request merged**
