### PR TITLE
Misc selection fixes

### PR DESCRIPTION
**Pull request by arvind**
A grab bag of fixes to selections. With this PR, single/multi selections should work with geographic projections. Interval selections are proving to be more tricky, and support will be forthcoming. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 500,
  "height": 300,
  "layer": [
    {
      "data": {
        "url": "data/us-10m.json",
        "format": {"type": "topojson","feature": "states"}
      },
      "projection": {"type": "albersUsa"},
      "mark": {
        "type": "geoshape",
        "fill": "lightgray",
        "stroke": "white"
      }
    },
    {
      "data": {"url": "data/airports.csv"},
      "projection": {"type": "albersUsa"},
      "selection": {
        "foo": {
          "type": "single",
          "fields": ["iata"],
          "nearest": true,
          "bind": {"input": "text"}
        }
      },
      "mark": "circle",
      "encoding": {
        "longitude": {"field": "longitude","type": "quantitative"},
        "latitude": {"field": "latitude","type": "quantitative"},
        "size": {"value": 10},
        "color": {
          "condition": {"selection": "foo", "value": "red"},
          "value": "steelblue"
        }
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by arvind** [comment]
It looks like the build is failing with this spec due to the change in 03a647e. The data transform pipeline is pretty complex, so I'm not overly confident of any changes I make here, so some help would be appreciated @domoritz. The high-order bit is that, whenever new tuples are produced, if `requiresSelectionId(model)` returns true, we need to insert an `IdentifierNode`. 

```json
{
  "data": {
    "values": [
      {"a": 0,"b": 28,"c": 0},
      {"a": 0,"b": 55,"c": 1},
      {"a": 0,"b": 23,"c": 2},
      {"a": 1,"b": 43,"c": 0},
      {"a": 1,"b": 91,"c": 1},
      {"a": 1,"b": 54,"c": 2},
      {"a": 2,"b": 81,"c": 0},
      {"a": 2,"b": 53,"c": 1},
      {"a": 2,"b": 76,"c": 2},
      {"a": 3,"b": 19,"c": 0},
      {"a": 3,"b": 87,"c": 1},
      {"a": 3,"b": 12,"c": 2},
      {"a": 4,"b": 52,"c": 0},
      {"a": 4,"b": 48,"c": 1},
      {"a": 4,"b": 35,"c": 2},
      {"a": 5,"b": 24,"c": 0},
      {"a": 5,"b": 49,"c": 1},
      {"a": 5,"b": 48,"c": 2},
      {"a": 6,"b": 87,"c": 0},
      {"a": 6,"b": 66,"c": 1},
      {"a": 6,"b": 23,"c": 2},
      {"a": 7,"b": 17,"c": 0},
      {"a": 7,"b": 27,"c": 1},
      {"a": 7,"b": 39,"c": 2},
      {"a": 8,"b": 68,"c": 0},
      {"a": 8,"b": 16,"c": 1},
      {"a": 8,"b": 67,"c": 2},
      {"a": 9,"b": 49,"c": 0},
      {"a": 9,"b": 15,"c": 1},
      {"a": 9,"b": 48,"c": 2}
    ]
  },
  "repeat": {"row": ["d","e","f"]},
  "spec": {
    "layer": [
      {
        "selection": {"sel": {"type": "single", "resolve": "global"}},
        "mark": "circle",
        "encoding": {
          "x": {"field": "a","type": "quantitative"},
          "y": {"field": "b","type": "quantitative"},
          "size": {"value": 100},
          "color": {"field": "c","type": "nominal"},
          "opacity": {"value": 0.25}
        }
      },
      {
        "transform": [{"filter": {"selection": "sel"}}],
        "mark": "circle",
        "encoding": {
          "x": {"field": "a","type": "quantitative"},
          "y": {"field": "b","type": "quantitative"},
          "size": {"value": 100},
          "color": {"field": "c","type": "nominal"}
        }
      }
    ]
  }
}
```

**Comment by domoritz** [comment]
🎉 Are there specific issues that can be closed when we merge this?

**Comment by arvind** [comment]
I don't think there are any existing GitHub issues (or at least, any assigned to me) that this PR addresses, unfortunately.

**Comment by arvind** [comment]
As this was a grab bag PR of selection fixes, I pushed three more to address specific issues that had been assigned to me. I've also expanded test coverage as requested.

**Pull request merged**
