### PR TITLE
Add multi-line tooltip example

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by domoritz** [comment]
That's pretty cool. Super useful and actually fairly easy to implement. I think this is one example that we could put into the main example gallery.

**Comment by jakevdp** [comment]
It's even easier to implement using Altair :smile: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/multiline_tooltip.py

**Comment by domoritz** [comment]
Would be cool to have in pdvega :-)

**Comment by kanitw** [comment]
This is very cool!  I wonder if it would be a bit nicer with `filled: true`?

**Pull request merged**
