### PR TITLE
Do not generate unnecessary top-level width/height signals for layout-based models

### PR DESCRIPTION
**Pull request by kanitw**
Fix https://github.com/vega/vega-lite/issues/2326

vega_editor

### CODE REVIEW

**Comment by domoritz** [comment]
Can you add an example spec that triggers this error?

**Comment by kanitw** [comment]
Do you mean add to the gallery?   (An example is in the screenshot)

**Comment by domoritz** [comment]
> Do you mean add to the gallery? (An example is in the screenshot)

More like the test specs.

**Comment by kanitw** [comment]
Done

**Comment by domoritz** [comment]
hmm, I don't understand why none of the top-level size signals disappear.

**Comment by kanitw** [comment]
@domoritz  -- splitting this into two commits should make it obvious now.

**Comment by domoritz** [comment]
Now I see it. Lgtm.

**Pull request merged**
