### PR TITLE
Make removeChild private -- people should use `node.remove()`

### PR DESCRIPTION
**Pull request by kanitw**

### CODE REVIEW

**Comment by domoritz** [comment]
The message is a bit confusing. What do you want people to use?

**Comment by kanitw** [comment]
corrected*

**Comment by invokesus** [comment]
`removeChild` is useful for inserting a new node in between two existing nodes.
E.g. in the Parse Merging case I want to insert a new node and only mutate(not remove) the existing nodes to keep only the conflicting parse fields.
ie. I want do 
```
A.removeChild(B);
B.parent(D);
```
and same for C
```
  A                          A -D
 / \              ->           /\
B   C                         B' C'
                                    
 ```
Maybe writing an `insert` method in `DataFlowNode` makes sense.

**Comment by kanitw** [comment]
I see.

Suppose we have the follow structure where B and C are parse nodes.

```
     A
   /   \
   B   C
   |   |
   D   E
```

One possible solution is to merge C into B (so we get B' and C', supposes some part of C isn't mergeable.) since the first one is always mergeable anyway. 


```
     A
    /   
   B'   
  /  \   
  D   C'
      |
      E
```

**Comment by kanitw** [comment]
I'd say try to avoid using `removeChild` if possible, but if you really need it, that's fine.

**Pull request merged**
