### PR TITLE
Smart alignment of header titles based on angle (similar to axis labe…

### LINKED ISSUE #4586: Smart alignment based on angle for header
(We already do this for axis, but not for header.)

### PR DESCRIPTION
**Pull request by domoritz**
…ls). Fixes #4586.

### CODE REVIEW

**Comment by kanitw** [comment]
LGTM.  Feel free to merge after you fix test (and test it comprehensively).

**Comment by domoritz** [comment]
I tested in the editor and since we are now using the same codepaths, we use the axis tests. I'm just not sure about wrapped facets yet.

**Comment by EvsChen** [comment]
Thanks @domoritz! I tried testing locally with `labelAngle=90, 180, 270, 330` using `facet_custom_header.vl.json` and it looks good.

**Comment by domoritz** [comment]
Excellent. Thanks!

**Comment by domoritz** [comment]
A good test example

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {
        "a": "AAAAAAA"
      },
      {
        "a": "BBBBBBB"
      },
      {
        "a": "CCCCCCC"
      },
      {
        "a": "DDDDDDD"
      }
    ]
  },
  "mark": "point",
  "encoding": {
    "row": {
      "field": "a",
      "type": "ordinal",
      "header": {
        "labelAngle": 40
      }
    }
  }
}
```

**Comment by domoritz** [comment]
I've tested it with the new facet wrap and it works well.

**Pull request merged**
