### PR TITLE
Upgrade to Vega 5.3.4

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
Why is the rect_binned_heatmap.svg changing?

**Comment by domoritz** [comment]
> Why is the rect_binned_heatmap.svg changing?

@jheer do you have an explanation?

**Comment by kanitw** [comment]
I wonder if it's simply because we merge something without rebasing?

**Comment by domoritz** [comment]
This is the editor with 5.3.2

image

**Comment by kanitw** [comment]
> Fix bin boundary floating point errors. (#1737)

Maybe the bin boundary get shifted by a little bit? IDK

**Comment by domoritz** [comment]
It looks very different, though. 

Screen Shot 2019-03-31 at 23 31 15

**Comment by kanitw** [comment]
I'm rebasing -- let's see if it's still dramatically different after the null fixes is included.

**Comment by jheer** [comment]
Small changes to histogram bins can have major effects, so that may be what is happening here? On the other hand, no Vega test specs changed when I updated the binning math. In any case, I added a lot of tests to double check the binning fix...

**Comment by kanitw** [comment]
Ok I've checked by writing a [spec to filter manually](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoBmOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSlU3Co2Sx5ilQF91ESHiPolsAGbcjVDMAbVAId19GMTxkIzMDb00QjXCwA0jkMSScSABJAFkAEQAhAH0AJR1GJWo1KAp0CWywT1ZkVxTw9Lssszyissq8atrVKGoYswAODtSIbszm-pKKqpq6yGjpugAmWbmF3pzy7gJkJVKAFW4MPG57VeH1scgGprNW9rcDyAyjqBOZwu11u91gjxGGwmyDMAE4AAz7VKHJaAmLAm46MEQ55QLY4WEAVmcnQAuiSIM5Sd9IBgjABrPrsdBxGnneDcTSQ-SdSAAD3ikHQ1GoRmEkxyHNYSjwGzwAE9CDCcgBHVjeYa6YZUSAUsD7SAcpSRWo81KvOwAd3inXcsE83Hpyqgnm8sEILPOss6epJJKAA).  The new version is more accurate.

image


The new version (right) seems also smoother than the older one.

image

**Comment by jheer** [comment]
Thanks @kanitw! In hindsight, the earlier version "clearly" shows striation artifacts of the floating point error. This is a nice example to hold on to for future sharing / teaching.

**Pull request merged**
