### PR TITLE
docs: correct + update utc related examples

### PR DESCRIPTION
**Pull request by haldenl**
Looks like #5780 didn't properly regenerate examples.

### CODE REVIEW

**Comment by domoritz** [comment]
Screen Shot 2020-01-29 at 11 03 01

**Comment by kanitw** [comment]
The examples are correct, not sure which one is incorrect. I'd recommend looking at each of them in the docs.

**Comment by domoritz** [comment]
Okay. I was just confused that the first example changes the label angle. It doesn't look good to me.

**Comment by kanitw** [comment]
> Okay. I was just confused that the first example changes the label angle. It doesn't look good to me.

The old label was bad anyway.

**Pull request merged**
