### PR TITLE
Update Mark Config

### PR DESCRIPTION
**Pull request by kanitw**
https://github.com/vega/vega-parser/blob/master/src/config.js

(Let's merge after Vega-3.0.0-beta.23 is released.)

### CODE REVIEW

**Comment by kanitw** [comment]
Hmm somehow travis is not running ><"

**Comment by domoritz** [comment]
Ready?

**Comment by kanitw** [comment]
Everything good except https://github.com/vega/vega-lite/issues/1995, which should be dealt with later :)

**Comment by domoritz** [comment]
Cool, I'll wait for you to merge https://github.com/vega/vega-lite/pull/1957

**Pull request merged**
