### PR TITLE
hconcat -> hConcat and vconcat -> vConcat

### PR DESCRIPTION
**Pull request by domoritz**
Ref #2402

### CODE REVIEW

**Comment by domoritz** [comment]
@kanitw Do you know why this is not passing? It works on my machine and I have no idea what I'm missing.

**Comment by kanitw** [comment]
IDK -- but using this logic here: https://github.com/vega/vega-lite/issues/2402#issuecomment-303457414 we shouldn't make it camelcase anyway.

**Comment by domoritz** [comment]
@kanitw Did you see https://github.com/vega/vega-lite/pull/2404/commits/6e70f955eae53f7b929d5e558be806222c4fc25a?

**Comment by kanitw** [comment]
Nope.  Seeing it now I wonder why we need to use ES2016 syntax for a node script anyway.

**Comment by domoritz** [comment]
Well, the point was that we used require to load JSON and had an unused import. I cherry picked it.

**Pull request closed without merging**
