### PR TITLE
Clarify resolve docs. #3077

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
LGTM.  I just correct positional channels to position channels (either is fine but we use "position channels" elsewhere in the docs.  

Maybe add warnings for the logger too? (So users can notice without needing to look at the document.)

**Comment by domoritz** [comment]
In https://github.com/vega/vega-lite/blob/master/site/docs/composition/resolve.md we say positional.

**Comment by kanitw** [comment]
Then let's change all occurrences of positional to position.
The reason is that we have "Mark Property Channel" / etc. which are compound nouns too, so "Position Channels" is more consistent.

**Comment by domoritz** [comment]
It still sounds odd to me but I'm not a native speaker either. What does
@jheer use in the Vega docs?

**Comment by kanitw** [comment]
In Vega, there is no distinction between them since they all have the same types.

**Comment by domoritz** [comment]
I think "position channel" is already taken for the x and y location. "Positional" imo includes length. 

Cleveland and McGill

image

**Pull request merged**
