### PR TITLE
Don’t add facet model name to data source. Fixes #2731

### LINKED ISSUE #2731: Trellis Barley example refers to undefined data source
This is first introduced in the facet of facet PR.  

Uncaught Error: Undefined data set name: "scale_trellis_barley_child_main"
"scale_trellis_barley_child_main"

(If you want to fix, please fix it in https://github.com/vega/vega-lite/pull/2730 so I can reapply facet of facet to hotfix branch and work on relevant issues from there.)

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
I reran examples after trashing node modules and running yarn. No idea why the output changes.

**Comment by domoritz** [comment]
@kanitw Okay, I even cleared my node modules folder and it still shows differences. Can you try to rebuild?

**Comment by arvind** [comment]
Looking at the diffs, it appears to be exclusively differences in axis title and legend positioning. Is there some possible upstream/downstream change that's being inadvertently pulled in? E.g., #2745?

**Comment by kanitw** [comment]
I'll try to rebase both hotfix-facet and this branch and see if there is still a problem.

**Comment by kanitw** [comment]
Yay, it is not problematic anymore!

**Pull request merged**
