### PR TITLE
Use faster json schema validator and remove color format.

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
Why remove color format?

**Comment by domoritz** [comment]
We didn't set it consistently and so I'd rather remove it. Is there a specific use case for it?

**Comment by kanitw** [comment]
I don't know. I think you added it?

**Comment by domoritz** [comment]
I added it when we still used it to generate the properties editor in polestar.

**Comment by kanitw** [comment]
@domoritz oops.  Then it's not good to remove it then!

**Comment by kanitw** [comment]
It's weird that you're suggesting to remove it despite the obvious utility!

**Comment by kanitw** [comment]
I know we don't have property editor right now, but I can't imagine away to know if a field is color in polestar without this!

**Comment by domoritz** [comment]
Not reliable but you could assume that stroke, fill, and color are all colors. Anyway, I'm happy to add it again if we need it but since we didn't use it consistently, I removed it.

**Comment by kanitw** [comment]
Instead of removing it, the right solution is to make it consistent ....

**Comment by domoritz** [comment]
There are two consistent states: use it nowhere and ensure that whenever we use a color, we specify the format.

**Comment by kanitw** [comment]
And the "use it nowhere" is not the ideal one...

**Pull request merged**
