### PR TITLE
Allow titles of type FieldDefBase to be used with TitleMixins [WIP]

### PR DESCRIPTION
**Pull request by Saba9**
As mentioned by @kanitw in #4254 a cleaner approach to fixing the problem of differing title behavior between specs which have had extracted transformations and those without is to allow the `title` field in `TitleMixins` to be of type `string | FieldDefBase<string>[]` where the latter type is used to define the correct implicit title.

### CODE REVIEW

**Comment by Saba9** [comment]
For some reason the schema build process fails and throws an exception stating that "The call stack size exceeded" after making the type change in `guide.ts`. Not sure what's going on with that.

**Comment by domoritz** [comment]
As discussed, increase the stack size.

**Comment by kanitw** [comment]
Is this still needed? If not, please close.

**Comment by Saba9** [comment]
There are a certain specs which I believe are impossible to extract transforms from while maintaining the same output without this. I stopped working on this for a period of time because of the talk of extracting transformations from Vega rather than VL, however, since it was concluded that we need transformation extract for composite marks it is still relevant.

I'll work on merging master into this branch and getting it ready for merging.

**Comment by Saba9** [comment]
Replaced by #4967

**Pull request closed without merging**
