### PR TITLE
Include `reflectX` and `reflectY` properties in projection

### PR DESCRIPTION
**Pull request by mattijn**
This PR addresses https://github.com/vega/vega-lite/issues/4723. 

It adds two new properties, `reflectX` and `reflectY` within the `projection` interface.

In https://github.com/vega/vega-lite/issues/4723 it was mentioned that projection `identity` was not included in the schema, but from what I can see at https://vega.github.io/schema/vega-lite/v3.json this is already included. 

The `identity` projection was missing from the documentation though and this PR includes the `identity` projection in the docs including the usage of `reflectX` and `reflectY` as is documented in Vega.

### CODE REVIEW

**Comment by mattijn** [comment]
Is there anything I can do to support the review process?

**Comment by domoritz** [comment]
Sorry, we've been super swamped. Can you make sure that the test pass on Travis?

**Comment by kanitw** [comment]
I believe this is redundant with #4785 which is merged.  Feel free to reopen if I'm wrong.

**Comment by mattijn** [comment]
You're right. This PR was done manually on github.com, where the other was done by forking the repo, clone the fork locally, create a branch on it, apply the changes in VSCode, build locally, test locally, publish branch to the fork and PR from there.

**Pull request closed without merging**
