### PR TITLE
refactor: simplify child names

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
So weird, the runtime tests are failing on my machine as soon as I modify the names of children a bit.

**Comment by kanitw** [comment]
I get similar errors, maybe there is another part of selection code that has these patterns fixed?

**Comment by domoritz** [comment]
I looked but couldn't find it. Something about the runtime tests is wrong, I think. I can run the specs that are used in the tests in the editor without problems.

**Comment by arvind** [comment]
Seeing this via email. One immediate thought: the runtime tests require a built version of Vega-Lite in “build/“. So maybe the discrepancies you’re seeing are a result of that?

-Arvind
-----
http://vis.csail.mit.edu/

**Comment by domoritz** [comment]
Thanks for chiming in @arvind. I'm running `yarn build && yarn test:runtime:generate` and still get these kinds of errors. 


```
  ● interval selections at runtime › in repeat views › should have one selection instance per intersect view

    TypeError: Cannot read property 'getBoundingClientRect' of null

      at coords (http:/0.0.0.0:8000/test-runtime:49:25)
      at brush (http:/0.0.0.0:8000/test-runtime:66:28)
      at __puppeteer_evaluation_script__:1:1
      at Suite.<anonymous> (test-runtime/resolve.test.ts:71:11)

  ● interval selections at runtime › in facet views › should have one global selection instance

    TypeError: Cannot read property 'getBoundingClientRect' of null

      at coords (http:/0.0.0.0:8000/test-runtime:49:25)
      at brush (http:/0.0.0.0:8000/test-runtime:66:28)
      at __puppeteer_evaluation_script__:1:1
      at Suite.<anonymous> (test-runtime/resolve.test.ts:36:9)

  ● interval selections at runtime › in facet views › should have one selection instance per union view

    expect(received).toHaveLength(expected)

    Expected length: 2
    Received length: 1
    Received array:  [{"fields": [{"channel": "y", "field": "b", "getter": {"fields": ["b"], "fname": "b"}, "type": "R"}], "unit": "child_layer_0__facet_row_1", "values": [[91, 27]]}]

      74 |               const parent = parentSelector(specType, i);
      75 |               const store = await page.evaluate(fn(specType, i, parent));
    > 76 |               expect(store).toHaveLength(i + 1);
         |                             ^
      77 |               expect(store[i].unit).toMatch(unitNameRegex(specType, i));
      78 |               await testRender(`${resolve}_${i}`);
      79 |             }

      at test-runtime/resolve.test.ts:76:29
      at fulfilled (node_modules/tslib/tslib.js:110:62)

  ● interval selections at runtime › in facet views › should have one selection instance per intersect view

    expect(received).toHaveLength(expected)

    Expected length: 2
    Received length: 1
    Received array:  [{"fields": [{"channel": "y", "field": "b", "getter": {"fields": ["b"], "fname": "b"}, "type": "R"}], "unit": "child__facet_row_1", "values": [[91, 27]]}]

      74 |               const parent = parentSelector(specType, i);
      75 |               const store = await page.evaluate(fn(specType, i, parent));
    > 76 |               expect(store).toHaveLength(i + 1);
         |                             ^
      77 |               expect(store[i].unit).toMatch(unitNameRegex(specType, i));
      78 |               await testRender(`${resolve}_${i}`);
      79 |             }

      at test-runtime/resolve.test.ts:76:29
      at fulfilled (node_modules/tslib/tslib.js:110:62)

Test Suites: 3 failed, 3 passed, 6 total
Tests:       27 failed, 33 passed, 60 total
Snapshots:   0 total
Time:        3.867s, estimated 10s
```

I can dive deeper into this later.

**Comment by arvind** [comment]
Aha! That’s happening because the test can’t find the specific SVG elements, which are queried for using child names  hardcoded here: https://github.com/vega/vega-lite/blob/master/test-runtime/util.ts#L53

-Arvind
-----
http://vis.csail.mit.edu/

**Comment by domoritz** [comment]
Wow, how did I miss that. Thanks!

**Pull request merged**
