### PR TITLE
Make `normalize` in fieldDef.ts  not causing side effect.

### PR DESCRIPTION
**Pull request by kanitw**

### CODE REVIEW

**Comment by domoritz** [comment]
@kanitw what's the status of this? Code looks good to me.

**Comment by kanitw** [comment]
Something is failing and i dont have time to fix it yet. Feel free to take it over.  This should be easy

**Comment by domoritz** [comment]
K, rebased and will check what needs to be done.

**Comment by domoritz** [comment]
Well, I didn't make any changes but tests are passing now...

**Pull request merged**
