### PR TITLE
Replace all uses of templates with signals.

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
LGTM except that I think we should use string template (``) to avoid `\'` and `\"`

**Comment by domoritz** [comment]
Done. Let's keep the two commits separate.

**Comment by domoritz** [comment]
Not sure why you squashed the commits but okay.

**Comment by kanitw** [comment]
I look at the diff and it seems natural to have this in one commit? 

The main semantic = template => signal -- the string template seems more like a stylistic change of the main change. So I prefer to lessen our work when we read through commit lists in vg3 to update release note.  :)

**Pull request merged**
