### PR TITLE
docs: add heat lane example

### PR DESCRIPTION
**Pull request by jonmmease**
As discussed on twitter (https://twitter.com/domoritz/status/1546869138370355201), this PR adds a new gallery example for the heat lane visualization type described in https://www.smashingmagazine.com/2022/07/accessibility-first-approach-chart-visual-design/.

visualization

Thanks!

### CODE REVIEW

**Comment by jonmmease** [comment]
I'm a bit confused by the validation error messages

**Comment by domoritz** [comment]
Take a look at the contributing guide. What specifically confuses you?

**Comment by jonmmease** [comment]
The CI test failure prints this regarding the new `bar_heatlane.vl.json` spec:

> Received: "must have required property 'mark', must have required property 'facet', must have required property 'as', must have required property 'bin', must have required property 'calculate', must have required property 'density', must have required property 'filter', must have required property 'flatten', must have required property 'fold', must have required property 'impute', must have required property 'joinaggregate', must have required property 'loess', must have required property 'lookup', must have required property 'quantile', must have required property 'regression', must have required property 'timeUnit', must have required property 'sample', must have required property 'stack', must have required property 'window', must have required property 'pivot', must match a schema in anyOf, must have required property 'repeat', must have required property 'repeat', must match a schema in anyOf, must have required property 'concat', must have required property 'vconcat', must have required property 'hconcat', must match a schema in anyOf"

The spec renders fine, but it looks like there are schema validation errors that don't make sense to me.

**Comment by jonmmease** [comment]
Ok, I think I was just missing an `"as"` key. Thanks for taking a look!

**Comment by domoritz** [comment]
Schema validation errors are often super cryptic. I usually check in the editor to find out what's wrong.

**Comment by domoritz** [comment]
I can manually make a copy of this pull request but I wonder whether you can add a PAT to your fork so that the "Format, Schema, and Examples" action runs. It should rebuild the images and Vega specs.

**Comment by jonmmease** [comment]
>  I wonder whether you can add a PAT to your fork

Happy to try, but I'm not sure what this means

**Comment by domoritz** [comment]
The pull request template describes how to add a PAT: https://github.com/vega/vega-lite/blob/next/.github/PULL_REQUEST_TEMPLATE.md. It's needed so that the GitHub action can push changes to your fork. If you can't figure it out in a short time, I will just make a copy of your pull request in this repo, which will trigger the build here.

**Comment by jonmmease** [comment]
ohh, sorry I missed that from the template. I can do it this evening, but feel free to make a copy if you're available before that.

**Comment by jonmmease** [comment]
I tried creating a secret with `public_repo` permissions:
Screen Shot 2022-07-20 at 4 56 12 PM
 
And then adding it as a secret named `GH_PAT` to my fork of vega-lite
Screen Shot 2022-07-20 at 4 56 21 PM

I closed and opened the PR to restart CI. All the tests that run passed but `Format, Schema, and Examples` still didn't run.  I also tried pushing an empty commit to trigger CI and saw the same result.

In the `check.yml` workflow config where the "Format, Schema, and Examples" job is, the trigger is:
```
on:
  push:
    branches:
      - '**'
```
Would you expect this to run in a fork?  I wonder if there should be a `pull_request` trigger as well:
```
on:
  push:
    branches:
      - '**'
  pull_request:
```
I would be interested to work this out so that things can go more smoothly next time.

**Comment by jonmmease** [comment]
I don't have any ideas on what to try, so it might be better for you to copy it a separate PR. Thanks!

**Comment by domoritz** [comment]
Copy in https://github.com/vega/vega-lite/pull/8353

**Pull request closed without merging**
