### PR TITLE
Remove unused browserify-shim

### PR DESCRIPTION
**Pull request by kanitw**

### CODE REVIEW

**Comment by jheer** [comment]
Just be careful that this does not break the build process for other tools
that package up vega-lite in a browserify project.

**Comment by domoritz** [comment]
Such as the ipython vega project.

**Comment by kanitw** [comment]
@domoritz   Do you mean this PR break ipython vega project?  

The motivation for this PR is actually making my CompassQL buildable.   (It's complaining about Vega-Lite's browserify-shim, which we actually do not use.

**Comment by domoritz** [comment]
I have to try. Unfortunately the build is already broken as documented in https://github.com/vega/vega-lite/issues/1372\.

**Comment by domoritz** [comment]
I don't have build problems in ipyvega, which uses webpack or vl-shorthand (on the new branch), which uses rollup. The only browserify project we tested with is compassql. 

@arvind Let us know if this causes build issues in lyra.

**Pull request merged**
