### PR TITLE
Revert "Don't use VSCode organize import anymore"

### PR DESCRIPTION
**Pull request by kanitw**
This reverts commit bf944beb4829874b8a8170f4b09eb70dda4c1ed8.

### CODE REVIEW

**Comment by domoritz** [comment]
Has the issue is vscode been fixed? If not, I'd say use this in your local settings but don't force everyone to use it.

**Comment by kanitw** [comment]
> Has the issue is vscode been fixed? If not, I'd say use this in your local settings but don't force everyone to use it.

I don't think so.  We haven't reported it.  

In any case, once you start writing a lot of code and have to remove imports manually. 
The undo thing isn't as annoying as required manual work.

**Comment by domoritz** [comment]
I filed https://github.com/Microsoft/vscode/issues/54411. Let's close this until it is resolved.

**Comment by kanitw** [comment]
Is it VSCode's bug?  Isn't it prettier plugin's?

**Comment by domoritz** [comment]
Prettier takes care of formatting but not the import organization. I should check whether this bug only occurs with the plugin.

**Comment by domoritz** [comment]
It's a vscode bug.

**Pull request closed without merging**
