### PR TITLE
Make encoding & mark required spec properties

### PR DESCRIPTION
**Pull request by mprudhom**
This will also use the new typescript-json-schema `--required` flag to include required properties in the JSON schema.

### CODE REVIEW

**Comment by kanitw** [comment]
Looks like you try to squash/amend your two commits but forgot to add `--amend`.  
Do you want to squash these two commits before we merge?

**Comment by mprudhom** [comment]
Squashed.

**Comment by kanitw** [comment]
Hmm, looks like there are even more commits.  By "squash", I mean http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html.

**Comment by mprudhom** [comment]
OK, it should really be squashed now.

**Comment by kanitw** [comment]
Awesome! Thanks :) 

FYI, instead of closing and re-push the branch and then reopen PR, you can also do `git push -f`.

**Pull request merged**
