### PR TITLE
Always add parse even for numbers. Fixes #4988

### LINKED ISSUE #4988: Quantitative data from CSV is sorted alphabetically rather than numerically
Reported in https://github.com/altair-viz/altair/issues/1531

Consider the following spec ([editor link](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSBXATgGxSgAt54AHAZ2QHpqdYB3AOgHMBLeIrAIywoFMcAYwD2AO3j8JTUQFtqATxHiWReXETVZsCpJzUyIhoID6Q3ADd+MihcjgwAXwA0DyNpwBrQsEjwFZPyEkHhsYkHOUIZh8ITwOFj8Lm5SotBhLD4OmAAePn4BQaiQAI5YsBIcCGxWkJGQAGZs-HjQwQDqYdBgFIH83QAU8hQAlJDJGFAK+f6BwWUV8FVLtfVNLW3FAPJY5LtghsY4YAOe7WOODpeOQA)):
```json
{
  "data": {
    "url": "https://raw.githubusercontent.com/yoonghm/data/master/power_curve.csv"
  },
  "mark": {"type": "line", "point": true},
  "encoding": {
    "x": {"type": "quantitative", "field": "Wind speed (m/s)"},
    "y": {"type": "quantitative", "field": "Output power (kW)"}
  }
}
```
visualization (94)

I would expect based on the quantitative encoding that the x-axis would be sorted numerically, but it is sorted alphabetically by the string representation of the number. This of course can be fixed by specifying an appropriate mapping for ``data.format.parse``, but I think this default behavior should be considered a bug.

### PR DESCRIPTION
**Pull request by domoritz**
Screen Shot 2019-05-26 at 20 20 17

### CODE REVIEW

**Comment by domoritz** [comment]
Let's make sure this does not break our optimizations.

**Comment by kanitw** [comment]
Test failing

**Comment by domoritz** [comment]
The transform extract isn't quite right yet. Maybe this is needed:

```
const formatType =
            isTypedFieldDef(channelDef) &&
            (isNumberFieldDef(channelDef) && !contains<any>(['count', 'distinct'], channelDef.aggregate)
              ? 'number'
              : channelDef.type !== TEMPORAL
              ? 'time'
              : null);
```

**Comment by domoritz** [comment]
replaced by https://github.com/vega/vega-lite/pull/4993

**Pull request closed without merging**
