### PR TITLE
Adding example: Co2 Concentration.

### PR DESCRIPTION
**Pull request by chanwutk**
Please:
- [ ] Make your pull request atomic, fixing one issue at a time unless there are many relevant issues that cannot be decoupled.
- [ ] Provide a test case & update the documentation under `site/docs/`
- [ ] Make lint and test pass. (Run `npm run lint`, `npm run test`, `npm run build:examples`, `npm run test:runtime:generate`.)
- [ ] Make sure you have rebased onto the `master` branch.
- [ ] Provide a concise title so that we can just copy it to our release note.
  - Use imperative mood and present tense.
  - Mention relevant issues. (e.g., `#1`)
  
Pro-Tip: https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3 is a nice article about writing a nice pull request.

Adding the example: Co2 Concentration, an example for argmin and argmax.

### CODE REVIEW

**Comment by domoritz** [comment]
Let's add some padding to the legend.

screen shot 2018-02-12 at 19 48 56

**Comment by domoritz** [comment]
Vega datasets has been updated

**Comment by domoritz** [comment]
Can you set padding.top to 0?

**Comment by chanwutk** [comment]
Do you mean padding of the whole graph or the padding of the legend?

**Comment by domoritz** [comment]
Just the legend.

**Comment by domoritz** [comment]
Nice!

**Pull request merged**
