### PR TITLE
Upgrade Vega, remove hack

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by jheer** [comment]
Make sure to grab Vega 3.0.4, just released.

**Comment by domoritz** [comment]
Looks like I have 3.0.4 already: https://github.com/vega/vega-lite/pull/3051/files#diff-8ee2343978836a779dc9f8d6b794c3b2R5536.

**Comment by kanitw** [comment]
Maybe squash merge and add explanation to the new squash commit?

**Comment by domoritz** [comment]
It was needed because we would generate specs that didn't pass schema validation.

**Pull request merged**
