### PR TITLE
nice:false is the default.

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
lol FYI, you can just edit the commit message when you "squash and merge", no need to force push.

**Comment by kanitw** [comment]
> Hmm, I would actually not squash this since it's nice to be able to revert a commit without having to deal with changed examples.

Well if you revert, you should revert the change examples too.  So I don't see why we shouldn't squash.  Otherwise we shouldn't squash any PR anyway.

**Comment by domoritz** [comment]
I think we should squash the code changes but not all PRs in general.

**Comment by domoritz** [comment]
Nonw of the generated SVG changes. I think this is good.

**Comment by kanitw** [comment]
> I think we should squash the code changes but not all PRs in general.

When should things be squashed and when should they not then?

**Comment by kanitw** [comment]
I'd argue that most PRs won't get reverted so the shorter commit logs the better when we go through and write the release notes.

**Comment by domoritz** [comment]
What if I want to look at what a commit changed? I have to scroll through a bunch of example changes as well. Le'ts discuss at the standup.

**Comment by kanitw** [comment]
> What if I want to look at what a commit changed? I have to scroll through a bunch of example changes as well.

`fn + arrow right = end` -- pretty easy to go to the end.

**Pull request merged**
