### PR TITLE
docs: relative frequency histogram

### PR DESCRIPTION
**Pull request by keckelt**
As discussed on Slack an example of a relative frequency histogram:

visualization

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/cars.json"},
  "transform": [{
      "aggregate": [{"op": "count", "as": "Count"}],
      "groupby": ["Cylinders"]
    }, {
      "joinaggregate": [{"op": "sum", "field": "Count", "as": "TotalCount"}]
    }, {
      "calculate": "datum.Count/datum.TotalCount", "as": "PercentOfTotal"
    }
  ],
  "mark": {"type": "bar", "tooltip": true},
  "encoding": {
    "x": {
      "field": "Cylinders",
      "type": "ordinal"
    },
    "y": {
      "field": "PercentOfTotal",
      "type": "quantitative",
      "axis": {
        "title": "Relative Frequency",
        "format": ".1~%"
        }
    }
  }
}

```

https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIeI+iWwAZtyOozAG1QCFCodGpqI2E8ZCCDbkIzSHhuViU8NXDYZIBhNIzIRwBdFzCoKLTCdgBPIMhcmoklTWRbSGKNCGcwEPLIOW5GJQiomLicYMhE5NhWANUob0ZkMU08gszFyHQcnEgAFW5dMXz0zJKusB6+sJT0MXhWMR0J8zx5ujOM0m0P1DoRxO3y22WSAAU2vBkBkAPLeIEPSBXRwaUoaSAYIwAazMBjwNUIb0g7BsWTc3G4YjwjCSOHcrGQzgxMNSmmG1DxV0gAA8ueUlis1nkmsNWu1FldXASick-OyRqYUWVXHV9FLBat1vtIUZoXCEcckSrQm5CcSAI6sTw03Q0qhqDU7HmMPa9DXS5hiYkAJVWOkYVDAADFolbWXUTXdfP4dMk6ABGAB+AFJkQLuiiNKjHEA

---

Please:

- [x] Make the pull requests (PRs) atomic. (Fix one issue at a time.) Multiple relevant issues that must be fixed together? Make atomic commits so we can easily review each issue.
- [x] Provide a concise title so we can easily copy it to the release note.
  - Use imperative mood and present tense.
  - Mention relevant issues. (e.g., `Fixes #1` / `Fixes part of #1`)
- [x] Lint and test (Run `yarn test`)
- [x] Rebase onto the latest `master` branch.
- [x] Review your changes before sending the PR (to ensure code quality).

### CODE REVIEW

**Comment by kanitw** [comment]
As discussed in https://github.com/vega/vega-lite/pull/5979, this plot is technically not histograms, since it doesn't involve binning. 

- [ ] I'd suggest to change to a different quantitative variable and do binning to make it a relative frequency histogram.

- [ ] Once adding bin, if you think this is different enough from ["percent of total example"](https://vega.github.io/vega-lite/docs/joinaggregate.html#percent-of-total).  Add the example to join aggregate docs and to the `examples.json` (in the advanced calculation section).  

I think it's pretty similar to "percent of total example", but given that relative frequency histogram is a common keyword, it's worth adding to the gallery so people can easily find them.

**Comment by keckelt** [comment]
> I think it's pretty similar to "percent of total example", but given that relative frequency histogram is a common keyword, it's worth adding to the gallery so people can easily find them.

Yes, I hit the example by accident when I was looking for something else in the examples and already looked for relative frequency histograms a couple of weeks before that.

>     * [ ]  I'd suggest to change to a different quantitative variable and do binning to make it a relative frequency histogram.

will do

>     * [ ]  Once adding bin, if you think this is different enough from ["percent of total example"](https://vega.github.io/vega-lite/docs/joinaggregate.html#percent-of-total).  Add the example to join aggregate docs and to the `examples.json` (in the advanced calculation section).

Okay. From my _Getting to know vega_-Expierence from the last months I would prefer it to be in the Histograms section of the examples because that's were I would expect it - like the log scaled one.

**Comment by domoritz** [comment]
> Histograms section of the examples because that's were I would expect it - like the log scaled one.

Makes sense to put it in the section (maybe we rename the section to distribution plots?) but not name it histogram.

**Comment by kanitw** [comment]
@domoritz  

> but not name it histogram.

@keckelt already agreed to change to a binned quantitative field, so it's fair to keep the name.

**Comment by keckelt** [comment]
I would then need to do a bin transform first and calculate the relative frequency based on that, right?

**Comment by kanitw** [comment]
> I would then need to do a bin transform first and calculate the relative frequency based on that, right?

Yep, calculate relative frequency based on each bin.

**Comment by keckelt** [comment]
New spec with Horsepower:

visualization


https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gkVgCcx2LTvSl46I7HmKVAX3URIeI+iWwAZtyOozAG1QCFCodkYVHHdWZFUob0ZkMU0zSAAJP1hkQm4Ad2QjNSh0WDSIpQB9TNscvO5CyA0IZzAQsJLqaiNhPGQgg25CNPhuViU8YshStIBhMYnIRwBdFw7IbrHCdgBPIMgK6qy6hqL4g8ij2sJ6wsrkJVTl5rBW9rDIOW5I9C6e2j6A0gQzSsFYAXOiWSqRwkHm40m5xmsIAKtxdGJ4YsVi83i9XNYxPBWGIdP1Ydo8OC6Fi8KRKdS0RjaVNkVAAAqFeAPPAAeW8TPQplxGlWGkgGCMAGszAY8DtCOTwjYpnhuNwxHhGMNokZYs5xQ9RppItRZS9IAAPc0dKBavBiJUZY65ApnfEJJIpcqXGrZG6nNQetwKp0AR1YnntOkYVCDtouUTaiaUyBhYBiyEcuLWrktACZZZAod7YYc-Sc7g9UgaPnt9MH7Y60gAlZIxqhgABiPQjRr2udCxa96cgnKM3Im-MFpkHrnlirSEajzA7-TnJUtjDKDdtrl8-h0aToAEYAH4AUiae9eIpaIEcQA

**Comment by keckelt** [comment]
I've added it to the examples.json but not to the joinaggregate documentation.
I think it doesn't add much to the "percent of total" example that is already there and may just be confusing with all the other transformations.

**Comment by keckelt** [comment]
I tried my branch in a local vega editor, but it didn't show up in the examples.

I noticed that those are pulled from github instead of the local (linked/node_modules) version:
https://github.com/vega/editor/blob/master/scripts/vendor.sh#L31

**Comment by domoritz** [comment]
> I tried my branch in a local vega editor, but it didn't show up in the examples.

Yep, because npm packages don't come with examples.

**Comment by kanitw** [comment]
Thanks a lot!  @keckelt

**Pull request merged**
