### PR TITLE
Add Image Mark

### PR DESCRIPTION
**Pull request by EricMende**
Initial commit of support of image mark.

I have not yet added Documentation.
I have also not yet tested whether all encodings work properly. However, basic input works.

I have duplicated the x() and y() fuctions in image.ts from rect.ts. In case there are no changes comming, one might want to use common fuctions instead.

Here is a working example:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "values": [
      {
        "url": "https://vega.github.io/images/idl-logo.png",
        "x": 0,
        "y": 0,
        "x2": 200,
        "y2": 200
      }
    ]
  },
  "mark": {
    "type": "image",
    "aspect": false,
    "align": "center",
    "baseline": "middle"
  },
  "encoding": {
    "url": {
      "field": "url",
      "type": "text"
    },
    "x": {
      "field": "x",
      "type": "quantitative"
    },
    "y": {
      "field": "y",
      "type": "quantitative"
    },
    "x2": {
      "field": "x2",
      "type": "quantitative"
    },
    "y2": {
      "field": "y2",
      "type": "quantitative"
    }
  }
}
```

### CODE REVIEW

**Comment by domoritz** [comment]
Hi @EricMende. Thank you so much for starting a PR. Let us know when it's ready for a review or if you have any questions. 

Related issue https://github.com/vega/vega-lite/issues/3758

**Comment by domoritz** [comment]
The data lives in vega-datasets. You can send a PR there. Alternatively, you can add images as base64 encoded data.

**Comment by domoritz** [comment]
@EricMende I'd love to get this feature in. Could you update the PR and add the data to Vega-Datasets?

**Comment by domoritz** [comment]
Ping @EricMende

**Comment by batu** [comment]
This sounds really cool to have! Is this still being worked on possibly? Or is there a way to contribute without knowing JS?

**Comment by kanitw** [comment]
We’ve not got the time to do it yet, and yeah you probably need to know JS to contribute

**Comment by kanitw** [comment]
Thanks for contributing. I've forked from this and start a new PR (with some additional fixes) in https://github.com/vega/vega-lite/pull/5060 so I'll close this for now.

**Pull request closed without merging**
