### PR TITLE
feat: (new examples) grouped histograms

### PR DESCRIPTION
**Pull request by keckelt**
As discussed on Slack an example of a grouped relative frequency histogram (and one with absolute frequencies):

# Grouped relative frequency histogram

visualization(1)

See the spec in [in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gUVgCcx2XAWJkhtBszacepZJubcjpbbtLx0R2PMUVAF91CEg8I3QlWAAzN1QzAG1QCFSodGpqI2E8ZCTgSG5CM0h4blYlPDV02BKAYXLKyCCAXVC0qCzywnYATyTIOt6JJU1kP2rIAHkjRiYVFo0IELAUjsg5bkYlDKycvJxkwuKcSFhWBNUoGMZkMU16xqqryHRa05m57YaKqtb2tKQLqsHr9Q7TWbzSCLNIrNaAnxieCsMQ6A5aHQXOg-SoeTGoOifeY4541EoABXG8GQlSmMSJ20gSzAQQ0bQ0kAwRgA1mZ4VA8L1COjIOxfGpmeFuNwxHhGCcwBFWMgNCEOQB3RiaFhmACMAAZ9e1IDSyi4lNQ+ZKymILip9Mywjc7g9TkMRmMJi9BcKSkpuKhtuhTFdHVBYIR0PBtpacCIAEwA1KQFDoT1WjrJuV4MTIT40qqndjcAgBiWZsKo9h3fNNIslvBlsOs2FJyAADwz62d9xKDJU3qFIv9gZ2IbD4WYubMShRYiTYXQ7cY71WYcr6GrYlXMWDsGQC6zjHg3J3e5VmZbqTVgLBa8zkB7rqglKM1Np9MhjMHvtOAEdWCibMdEYKhy3WJcVy7B9s2nU4ACU7hAqgwAAMWyADTV6MAAAphSMMB+wASnAh84iMDBCygfU6F1AA-ABSSAwGbZkb2TG03Gg5Mnz7L8BwFIc-QDINTDY1VjTKJQblje9kwoW51T5M4Im4bkRQiKII18AtmjbSDVwKTQA3QbYAHUtR1HBdSvVlWSAA).

# Grouped Histogram

visualization(2)

See the spec in [in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gUVgCcx2XAWJkhtBszacepZJubcjpbbtLx0R2PMUVAF91CEgMIwBrM1AIMLwAT0JkM0h2XzUNeO5uMTxGQjM8I1ZkDRCNSAB3Rk0WMwBGAAYm0KhkJXhuFyVqGKyoLrFWVBV9AbCAM0ZkMU1UgGEEiSVNZD81KETk1KVuVEYldFM2uKhYQnR4Q76cEQAmU7jIFHQ1o36zs8h8vDFkADyRhmSjwqXY3AI+0yX2eYnQ7FmQJBYJwaUheGhEzAQQGFW+AA9Pl9INNZvM0cimCpVFskik0XsDkcTtifsx-mYlKwxGInmF0ATGLBibDIPDEWIRThJsdYMh+c98vBItKwLKpWVYbizvjnglRc90NRqEZhHgGYNuKxQZsfvTUgBHVjoUHMHSMKiQPFPSBDNyGqYzOapKmHO3bS2QJmHY7e3XlNp+5TTW5gWLPCgzKoxSCwYrcSJR4qui6+DpgvUCoVq4CQTT7dCHADqtXqOAaOpxIFxQA).

---

Please:

- [x] Make the pull requests (PRs) atomic. (Fix one issue at a time.) Multiple relevant issues that must be fixed together? Make atomic commits so we can easily review each issue.
- [x] Provide a concise title so we can easily copy it to the release note.
  - Use imperative mood and present tense.
  - Mention relevant issues. (e.g., `Fixes #1` / `Fixes part of #1`)
- [x] Lint and test (Run `yarn test`)
- [x] Rebase onto the latest `master` branch.
- [x] Review your changes before sending the PR (to ensure code quality).

### CODE REVIEW

**Comment by domoritz** [comment]
I think the link is https://vega-js.slack.com/archives/C4R371X41/p1580475102053700

**Comment by kanitw** [comment]
Thanks for the PR.  However, I have several concerns about this PR. 

1) If we gonna add the examples, we should add them to the gallery otherwise no one would see them anyway. 

2) These plots are technically not [histograms](https://en.wikipedia.org/wiki/Histogram), since they don't involve binning.  It's more accurate to call them distribution plots.

3) We try to avoid redundant examples in the gallery, and the non-relative plots are actually not that different than a standard group bar examples. Thus, I don't think we should add it.

4) For the relative distribution plot, it's a bit confusing to me that the plot groups the bars by values rather than by their origins, so it takes more time for readers to understand what's the denominator for the percentage normalization. (It's good that the y-title at least includes the grouping information though.) 

Wouldn't it be better to map x to cylinders and origin to Columns, then we don't even have to explain the denominator in the y-title.

image


https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAWOgCtY3AHaQANOCgATdHkw5gUVgCcx2XAWJkhtBszacepZJubcjpbbtLx0R2PMUVAF91CEg8I3QlWAAzN1QzAG1QCFSodGpqI2E8ZCTgSG5CM0h4blYlPDV02BKAYXLKyCCAXVC0qCzywnYATyTIOt6JJU1kP2rIAHkjRiYVFo0IELAUjsg5bkYlDKycvJxkwuKcSFhWBNUoGMZkMU16xqqryHRa05m57YaKqtb2tKQLqsHr9Q7TWbzSCLNIrNaAnxieCsMQ6A5aHQXOg-SoeTGoOifeY4541EoABXG8GQlSmMSJ20gSzAQQ0bQ0kAwRgA1mZ4VA8L1COjIOxfGpmeFuNwxHhGCcwBFWMgNCEOQB3RiaFhmACMAAZ9e1IDSyi4lNQ+ZKAB5WjrXW73erDbZjCYvQXCkpKbiobboUzMtUImUXFT6ZlhG53B4fSGMj1CkU+v07UwA1LhZhidFKFFiDNhWCEdDwbaWnAiABMhdwyHQbrt9oF2eQnxpVVO7G4BF9EubUFR7Du7aaXZ7eD7kZZQYzkDBq2nkGjTtOlKM1Np9PjKkTXtOAEdWFE5bo5VR++t0NbGO9FwOs3gcyUAEp3HSMKhgABi2SPpv6Wso3iHQSn1OhdQAPwAUkgMBp1ZWE5zKMQ3CbQEV1jKAGV3AUk29X1-XTJcc2oGksLzMQxCDVVjTKJQbgre9MwoW51T5M4Im4bkRQiKJi18Dtmjna9bw4zRfXQbYAHUtR1HBdUQmdWSAA

**Comment by kanitw** [comment]
Ah I just saw https://github.com/vega/vega-lite/pull/5978, so I think if you agree that faceting by origin yields a better plot, I think it's probably best to only include the example in https://github.com/vega/vega-lite/pull/5978.

**Comment by keckelt** [comment]
> Ah I just saw #5978, so I think if you agree that faceting by origin yields a better plot, I think it's probably best to only include the example in #5978.

Fine for me. I created two PRs because this one is not that important given the first example. Only the difference between absolute/relative is clearer in this case.

> Wouldn't it be better to map x to cylinders and origin to Columns, then we don't even have to explain the denominator in the y-title.

I think there is no clear answer. It depends on whether you want to compare individual categories or the general distribution.

**Comment by kanitw** [comment]
> I think there is no clear answer. It depends on whether you want to compare individual categories or the general distribution.

I agree that if you analyze the data yourself and create the plots, faceting this way can be useful.  However, for audience that doesn't the create plot themselves, it is a bit more complex to understand.  Given we'll have https://github.com/vega/vega-lite/pull/5978, I'd prefer that we add that one and drop this PR. 

Thanks a lot for your contribution though. :)

**Pull request closed without merging**
