### PR TITLE
Make imports consistent. No newline between imports. Two lines after …

### PR DESCRIPTION
**Pull request by domoritz**
…the import block.

### CODE REVIEW

**Comment by kanitw** [comment]
If there is no linter / auto formatter applied, this won't be preserved anyway?

**Comment by domoritz** [comment]
No, but at least we have all imports in one block so we have fewer merge issues. We might get a linter but I'm waiting to hear back from a github issue. 

Can you merge it? Doesn't hurt to be more consistent.

**Comment by kanitw** [comment]
Did u automatically generate this somehow?

This will cause merge conflict disaster for my giant pr - so i dont know why u choose to do it now

**Comment by domoritz** [comment]
If you just do the same, it will be easy to do. Just remove all empty lines
between imports and you won't have any conflicts.

**Comment by kanitw** [comment]
> If you just do the same, it will be easy to do. Just remove all empty lines
between imports and you won't have any conflicts.

That's not true because I will modify the same line as you -- anyway I'll merge it despite its bad timing

**Pull request merged**
