### PR TITLE
Suppress all errors in JSON syntax highlighting

### PR DESCRIPTION
**Pull request by domoritz**
I saw an error on the config page and decided to just hide all errors. 

screen shot 2019-01-28 at 17 26 12

### CODE REVIEW

**Comment by domoritz** [comment]
Same as before we broke it (black text with no background).

**Comment by kanitw** [comment]
What about using js instead of JSON?

**Comment by domoritz** [comment]
We can experiment with js instead of json. I just wanted to not see errors everywhere anymore.

**Comment by kanitw** [comment]
I think JS is better as we'll still get syntax highlighting.

**Comment by domoritz** [comment]
Why don't we get syntax highlighting with json?

**Comment by domoritz** [comment]
@kanitw Let's merge this, okay?

**Comment by kanitw** [comment]
Try JS?

**Comment by domoritz** [comment]
Yeah, this is not relevant with #4587

**Pull request closed without merging**
