### PR TITLE
Use transform typings from vega-typings

### PR DESCRIPTION
**Pull request by invokesus**

### CODE REVIEW

**Comment by domoritz** [comment]
Next time try not to update everything in yarn.lock to isolate the change.

**Comment by kanitw** [comment]
I still see a lot of TODOs.  Why removing the WIP label?

**Comment by domoritz** [comment]
I think the todos are copies from the Vega typings?

**Comment by domoritz** [comment]
I rejected the typings PR but suggested a solution here. Ping me when this is ready.

**Comment by domoritz** [comment]
@invokesus Do you want to finish this PR?

**Comment by invokesus** [comment]
Yup!

**Comment by domoritz** [comment]
This probably needs to be redone.

**Pull request closed without merging**
