### PR TITLE
[WIP] Fix Scale Sorting 

### LINKED ISSUE #2069: Sorting values on a color legend.
I'd like to sort nominal values on color channel.
First I drew this,
```json
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
    "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "*",
        "type": "quantitative",
        "aggregate": "count"
      },
      "y": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "descending","op": "count"}
      },
      "color": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "ascending","op": "count"}
      }
    }
  }
```
Result : 

vega 14

Then I sorted with this spec with expecting to change an order of values on the color legend (USA->Japan -> Europe). 
```
{
    "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
    "data": {"url": "https://vega.github.io/vega-datasets/data/cars.json"},
    "mark": "bar",
    "encoding": {
      "x": {
        "field": "*",
        "type": "quantitative",
        "aggregate": "count"
      },
      "y": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "descending","op": "count"}
      },
      "color": {
        "field": "Origin",
        "type": "nominal",
        "sort": {"field": "*","order": "ascending","op": "count"}
      }
    }
  }
```
Result : 
vega 13

Hope to know how to sort values on legend and whether it is intended to change color values when sorting color channel.

### PR DESCRIPTION
**Pull request by kanitw**
Fix #2069

### CODE REVIEW

**Comment by domoritz** [comment]
@yhoonkim What is the story behind this?

**Comment by kanitw** [comment]
@yhoonkim volunteer to fix #2069, but haven't got a round to it yet.

**Comment by yhoonkim** [comment]
@kanitw 
Sorry for late!
When I worked this issue, I merged master branch to here first then worked. 
After pushed my commits(including merged master), it was too messy. So I cherry-picked only my commits to here and pushed again like this.
My commits passed all test well when I merged it with the current master branch.

**Comment by domoritz** [comment]
@yhoonkim What's the status of this PR? Do you need help finishing it?

**Comment by yhoonkim** [comment]
@domoritz I've waited for reviewing. I rebased this branch and requested again.

**Pull request closed without merging**
