### PR TITLE
Remove Vega-Lite Editor

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
- I don’t think gallery should become index.html.  index.html should be the Vega-lite’s project page, which we can easily copy vega’s project page and have 15 nice examples there that links to editor.  
Meanwhile, our gallery is a testing gallery, not example.   

- I think we should copy the functionalities for (1) save code in cookie (2) browser sync to vega-editor, it’s quite annoying when forgetting to save script there. 

- instead of having `gallery/bower.json` can we move those dependency to `devDependencies` in the main `bower.json`.  Or do something so we do not have to do `cd gallery && bower install` every time we check out new branches.

**Comment by kanitw** [comment]
No hurry on doing any of this though, we should do it when other more important things are done.

**Comment by domoritz** [comment]
Agree with all you points but certainly not today.

**Comment by domoritz** [comment]
Done. I haven't ported the cookie feature over to the editor yet. What are your thoughts on a landing page for vl?

**Comment by kanitw** [comment]
@domoritz  We can initially copy Vega's landing page, and replace vega examples with vega-lite examples.  That could be done in another PR though.

**Comment by kanitw** [comment]
LGTM except one thing:

Why do we need to validate in the gallery?  We already added validation to the unit test.

**Comment by domoritz** [comment]
Done

**Pull request merged**
