### PR TITLE
Lookup Selections + Index Chart Example

### PR DESCRIPTION
**Pull request by arvind**
Addresses #2765. This is a freshly rebased version of almost year-old code. I've marked it as draft to both verify the changes, but also debug dataflow issues I remember having around where the lookup transform and/or timeunit transforms would get added or rearranged.

### CODE REVIEW

**Comment by arvind** [comment]
After investigation, whatever dataflow issues we used to have back in 2018 seemed to have been resolved and the base functionality of this PR appears to work for the included index chart example.

@domoritz, I could use your help though. Right now, for the index chart example included in this PR, we are producing two data sets with this definition (named `data_1` and `data_3`). As far as I can tell, they are respectively being produced when we materialize a selection for the lookup transform, and for the explicit selection filter defined in the spec. It seems wasteful to have this duplication, but I'm not sure how I should change my additions of to the dataflow to be smarter about this. 

```json
{
      "name": "data_1",
      "source": "data_0",
      "transform": [
        {
          "type": "filter",
          "expr": "!(length(data(\"index_store\"))) || (vlSelectionTest(\"index_store\", datum))"
        }
      ]
    }
```

Would you mind taking a look? I'd like to get this resolved before doing unit testing since it may have implications for what gets generated. Thanks!

**Comment by domoritz** [comment]
Vega-Lite's dataset generation works in a few steps. First, we parse and generate a dataflow graph. This graph has dataflow nodes of various kinds. Once we built the complete graph, we run a number of optimizers to remove redundancy. The most important property of an optimizer is to be correct. We are very conservative and there are still a number of fairly simple optimizations we don't do. I suspect that the duplication you are seeing is one of those instances. We should never rely on the optimizer for correctness. If possible, try to write the unit tests in a way where they don't test the generated datasets.

Having said that, we have an optimizer that merges identical nodes at forks, which would cover the case you're seeing. I have to look at the dataflow graph visualization to see what's happening here.

**Comment by domoritz** [comment]
Before optimization:

image

After optimization:

image

It looks like what we need here is an optimizer to move the filter of invalid data up and then it would get merged. I won't have time to do this before the end of the month but I'm planning to spend some time on optimizations then.

**Comment by domoritz** [comment]
Sidenote: the filter invalid on the right side should probably come before the time unit node. Not sure who inserts that node.

**Comment by domoritz** [comment]
Can you squash the commits in this pr?

**Comment by domoritz** [comment]
Can you rebase and squash?

**Pull request merged**
