### PR TITLE
Supporting setting gap between binned bar 

### LINKED ISSUE #1337: Draw bar charts with binning without gaps
One could argue that we are binning a continuous domain and there should be no gaps. 

screen shot 2016-05-03 at 12 55 12

We still want the gaps for categorical data

screen shot 2016-05-03 at 12 58 40

What would be a bit annoying is that we have to offset the ticks by .5px so it is between the bars.

### PR DESCRIPTION
**Pull request by kanitw**
Fix #1337

Add `binBarOffset` for setting  gap between binned bar.

### CODE REVIEW

**Comment by domoritz** [comment]
Offset is definitely not the right word. `binBarSpacing`?

**Comment by kanitw** [comment]
renamed to `binnedBarSpacing`

**Comment by kanitw** [comment]
(ready for review)

**Comment by willium** [comment]
Is there a reason we don't let you specify/namespace the mark type you're config-ing?

**Comment by kanitw** [comment]
> Is there a reason we don't let you specify/namespace the mark type you're config-ing?

Are you saying you want `config.mark.bar.binSpacing`?

**Comment by willium** [comment]
More jus curious why this isn't already the structure. Was a little thrown off when working on themes, which seem to intersect weirdly with config

**Comment by kanitw** [comment]
> why this isn't already the structure

What is `this`? 

> Was a little thrown off when working on themes, which seem to intersect weirdly with config

@willium `config` is the theme for Vega-Lite.  
We have opportunity to provide more fine grain control here than in Vega.  
That said, it would be great to know what's missing in VL config that exists in Vega theme.

**Comment by domoritz** [comment]
Manually merged

**Pull request closed without merging**
