### PR TITLE
Fix default BoxPlot title

### PR DESCRIPTION
**Pull request by kanitw**

### CODE REVIEW

**Comment by kanitw** [comment]
@chanwutk  wonder if you can copy one of your error-bar test and modify it for boxplot test here? (Shouldn't take too much time - I hope)

**Comment by chanwutk** [comment]
Which errorbar test do you want me to copy?

**Comment by kanitw** [comment]
I assume you have one test for the title?

**Comment by chanwutk** [comment]
I don't have a test for titles, but I can create one.

**Comment by kanitw** [comment]
Let's close this since the title fix is in the `makeCompositeAggregatePartFactory` method that we gonna re-use.

**Pull request closed without merging**
