### PR TITLE
Use `update` encoding block for voronoi marks to ensure reactivity.

### LINKED ISSUE #4265: Combining selections
I am trying to create a set of charts that use two types of selections:

- overview + detail ([example](https://vega.github.io/vega-lite/examples/interactive_overview_detail.html)), using a selection on the bottom chart to drive the scales in the top chart.
- tooltip rule ([example](https://vega.github.io/vega-lite/examples/interactive_multi_line_tooltip.html)), using a hovering selection on the top chart to show a vertical rule that can be used as a tooltip of sorts.

As you can see, this works - sort of. The problem is that the tooltip in the second selection seems "unaware" of the scale change from the first selection.

cc: @arvind 

link to example: https://bl.ocks.org/ijlyttle/d82ccd24196e5c4447cb3270ffdc2ffc

spec from example:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/sp500.csv"
  },
  "vconcat": [
    {
      "layer": [
        {
          "width": 480,
          "mark": "area",
          "encoding": {
            "x": {
              "field": "date",
              "type": "temporal",
              "scale": {
                "domain": {
                  "selection": "brush"
                }
              },
              "axis": {
                "title": ""
              }
            },
            "y": {
              "field": "price",
              "type": "quantitative"
            }
          }
        },
        {
          "width": 480,
          "mark": "point",
          "encoding": {
            "x": {
              "field": "date",
              "type": "temporal",
              "scale": {
                "domain": {
                  "selection": "brush"
                }
              }
            },
            "y": {
              "field": "price",
              "type": "quantitative"
            },
            "opacity": {
              "value": 0
            }
          },
          "selection": {
            "tooltip": {
              "type": "single",
              "nearest": true,
              "on": "mouseover",
              "encodings": [
                "x"
              ],
              "empty": "none"
            }
          }
        },
        {
          "transform": [
            {
              "filter": {
                "selection": "tooltip"
              }
            }
          ],
          "mark": "rule",
          "encoding": {
            "x": {
              "field": "date",
              "type": "temporal",
              "scale": {
                "domain": {
                  "selection": "brush"
                }
              }
            }
          }
        }
      ]
    },
    {
      "width": 480,
      "height": 60,
      "mark": "area",
      "selection": {
        "brush": {
          "type": "interval",
          "encodings": [
            "x"
          ]
        }
      },
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal"
        },
        "y": {
          "field": "price",
          "type": "quantitative",
          "axis": {
            "tickCount": 3,
            "grid": false
          }
        }
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by arvind**
Fixes #4265 which is a result of either a bug or undocumented intended behavior in Vega (vega/vega#1460). Either way, this PR uses a workaround that fixes the issue.

### CODE REVIEW

**Comment by domoritz** [comment]
Let's wait for an answer from @jheer on the Vega issue before merging this.

**Comment by kanitw** [comment]
Link to corresponding Vega issue?

**Comment by domoritz** [comment]
vega/vega#1460 😛

**Comment by domoritz** [comment]
What needs to be done here?

**Comment by arvind** [comment]
We got the answer in the other issue, which confirms that this PR is indeed the correct way to address the problem. So we should merge.

**Comment by domoritz** [comment]
I merged master so we can squash and merge once tests pass.

**Pull request merged**
