### PR TITLE
Rename applications to ecosystem

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
I think the term application is confusing, but I'm not sure if ecosystem is better.

**Comment by domoritz** [comment]
It's definitely less confusing.

**Comment by domoritz** [comment]
When I see applications, I think of "apps" or "tools" rather than general "usages".

**Comment by domoritz** [comment]
https://parquet.apache.org/ uses "adopters".

**Comment by domoritz** [comment]
Another option is to have top level "tools" (for users) and "adopters" (to show how awesome we are).

**Pull request merged**
