### PR TITLE
docs: use penguins data for boxplots

### PR DESCRIPTION
**Pull request by domoritz**
We didn't have a simple boxplot with nominal data in the gallery. I called it just `boxplot.vl.json` since it's a very basic example.

### CODE REVIEW

**Comment by domoritz** [comment]
Done. I replaced all boxplots with penguins.

**Comment by kanitw** [comment]
Nice!  `boxplot_2D_horizontal` is very similar to `boxplot` -- do we really need to add `boxplot`?  Can we remove one of them?

**Comment by kanitw** [comment]
Damn, we got tricked by github actions again.

**Comment by domoritz** [comment]
Ups. Sorry about that.

**Comment by kanitw** [comment]
It's ok. This is UI's fault, not yours.

**Pull request merged**
