### PR TITLE
London

### LINKED ISSUE #3343: Add non-US geo examples
@jwoLondon, could you add the graticule.json file to vega-datasets so that we can add the example you sent us via email?

### PR DESCRIPTION
**Pull request by domoritz**
By @jwoLondon 

Fixes #3343

### CODE REVIEW

**Comment by jwoLondon** [comment]
Thanks. Looks good to me.

**Comment by domoritz** [comment]
Depends on https://github.com/vega/vega-parser/pull/69

**Comment by domoritz** [comment]
Also depends on #3356

**Comment by domoritz** [comment]
I'm just waiting for the 3.1 release of Vega.

**Comment by domoritz** [comment]
Can merge after #3393

**Pull request merged**
