### PR TITLE
Fix incorrect labelAlign in spec with top orient

### LINKED ISSUE #4491: Labels in top oriented axis is aligned incorrectly
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {"values": [
    {"source": 0, "destination": 0},
    {"source": 1, "destination": 1},
    {"source": 2, "destination": 2}
  ]},
  "mark": "rect",
  "encoding": {
    "y": {
      "field": "source",
      "title": "Source Server",
      "type": "ordinal"
    },
    "x": {
      "field": "destination",
      "title": "Destination Server",
      "type": "ordinal",
      "axis": {
        "orient": "top"
      }
    },
    "color": {
      "value": "indigo"
    }
  }
}
```

image

### PR DESCRIPTION
**Pull request by sirahd**
- fix #4491

### CODE REVIEW

**Comment by domoritz** [comment]
Can you add a few tests?

**Comment by jheer** [comment]
FYI, with the new Vega v5 `titleOrient` (legends) and `titleAnchor` (legends/axes) options, I've made changes to the Vega config and also have more logic for automatic determination of alignment and baseline when they are not explicitly specified. I don't know if that is relevant here, but at least wanted to call your attention to it, as the solution to some layout problems may actually be "do nothing at all".

**Comment by domoritz** [comment]
Oh, so we should see whether this new Vega logic is as smart as the logic we have currently implemented in Vega-Lite and maybe drop it entirely. @sirahd could you look into this? 

I also saw that this PR already has 100% test coverage so don't worry too much about tests for now.

**Comment by domoritz** [comment]
Let's revise this after this PR.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/issues/4632

**Pull request merged**
