### PR TITLE
For mark overlays, do not apply selection to the augmented layers yet.

### PR DESCRIPTION
**Pull request by kanitw**
(We will properly do that later in https://github.com/vega/vega-lite/issues/3702)

### CODE REVIEW

**Comment by domoritz** [comment]
What problem does this fix?

**Comment by kanitw** [comment]
We don't have a clear policy how to do it yet.  This resets the behavior to be "doing nothing".  The old code was weird anyway.

**Comment by kanitw** [comment]
We don't have a clear policy how to do selection for overlay / composite yet #3702 .  This resets the behavior to be "doing nothing".  The old code was weird anyway.

**Comment by domoritz** [comment]
Why was the old code weird? I don't think it's good to break selections for overlaid plots. Can you provide some examples where the old code was incorrect or what won't work anymore when we merge this?

**Comment by kanitw** [comment]
The old code remove selection from the area layer and add selection to both point and line overlays.  Isn't that weird?

**Comment by kanitw** [comment]
This PR makes the logic for overlay supposes to just add new overlay layers, but preseves selection to be in the original layer.  I think this is a reasonable standard logic.  We could have more sophisticated policy later.

**Pull request merged**
