### PR TITLE
index scale has discrete domain.

### PR DESCRIPTION
**Pull request by domoritz**
I'm not even sure whether these type annotations are still necessary.

### CODE REVIEW

**Comment by kanitw** [comment]
Nice catch.  They are indeed necessary since these are new concepts in Vega 3 and are recently introduced for the migration. 

I'll take a look and see if this break anything.  If not, I'll merge.

**Comment by domoritz** [comment]
Are the type annotations necessary or will TS infer them automatically?

**Comment by kanitw** [comment]
Oh, that part I don't know.  You might wanna test that :)

**Comment by kanitw** [comment]
Just tested.  We still need them!

**Comment by kanitw** [comment]
I also found a bug in `toSet`'s interface.

**Comment by domoritz** [comment]
Merge?

**Pull request merged**
