### PR TITLE
fix: constrain `isConditionalParameter` type parameter

### LINKED ISSUE #8465: Type error with Typescript 4.8
The following template parameter is throwing an error with TypeScript 4.8 because the template of `Conditional` type is restricted to a subset `Conditional<CD extends FieldDef<any> | DatumDef | ValueDef<any> | ExprRef | SignalRef>`

https://github.com/vega/vega-lite/blob/c97e30a8da569aabab7f348673899f43aa3b8825/src/channeldef.ts#L158

The error raised is 

```
  ../node_modules/vega-lite/build/src/channeldef.d.ts(63,66): error TS2344: Type 'T' does not satisfy the constraint 'SignalRef | ExprRef | FieldDef<any, any> | DatumDef<string, SignalRef | DateTime | ExprRef | PrimitiveValue> | ValueDef<...>'.
    Type 'T' is not assignable to type 'DatumDef<string, SignalRef | DateTime | ExprRef | PrimitiveValue>'.
```

Seen in https://github.com/jupyterlab/jupyterlab/actions/runs/3217544851/jobs/5260639447

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #8465

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @fcollonval!

**Comment by jtpio** [comment]
@domoritz just curious if you were able to have a look at this PR? Thanks!

**Comment by domoritz** [comment]
Thank you for the pull request and your patience!

**Comment by jtpio** [comment]
Thanks @domoritz!

**Pull request merged**
