### PR TITLE
Remove link to Vega-Lite 1

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
Why removing? Shouldn't people still have access the older version if they still use it?

**Comment by domoritz** [comment]
They can still find it but I want to declutter the homepage.

**Comment by kanitw** [comment]
Meh..

**Comment by kanitw** [comment]
I don't feel like it's helping that much to remove this.

**Comment by domoritz** [comment]
Okay. I don't feel strong about it.

**Comment by domoritz** [comment]
We actually have a link in the readme and I think that's sufficient. https://github.com/vega/vega-lite

**Comment by kanitw** [comment]
Lol that s pretty much undiscoverable

**Comment by domoritz** [comment]
But also not super important ;-)

According to our Analytics, vega-lite-v1 gets 0.8% of the traffic that vega-lite gets and those are probably mostly bots. Also, nobody navigates to v1 from the home page.

**Comment by kanitw** [comment]
Whatever

**Pull request merged**
