### PR TITLE
Use standardized field prefixes for generated fields [WIP]

### PR DESCRIPTION
**Pull request by Saba9**
Addresses #4237. Currently only implemented for the count field.

### CODE REVIEW

**Comment by Saba9** [comment]
A few of our example specs such as `layer_text_heatmap` make reference to the `count_*` field. They'll have to be changed in order to work entirely. This also means that these changes will break any user's specs referencing internally generated fields.

**Comment by domoritz** [comment]
> This also means that these changes will break any user's specs referencing internally generated fields.

Excatly for this reason I want to make the names more explicit so that we make that expectation clear. 

cc @kanitw

**Comment by kanitw** [comment]
Are there that many specs like that?   I think for `layer_text_heatmap` we should just manually extract the transform so we don't have to "hack" like this.

**Comment by Saba9** [comment]
It's only in `layer_text_heatmap` and `layer_text_heatmap_normalized`.

**Comment by domoritz** [comment]
`__foo` is easier to check (you just check the first two characters). I don't care about symmetry.

**Comment by kanitw** [comment]
ok whatever. It's not a big deal.

**Comment by domoritz** [comment]
Wer're now doing this for count. @Saba9 please redo this for other internal fields.

**Pull request closed without merging**
