### PR TITLE
Create Error Band Document

### PR DESCRIPTION
**Pull request by chanwutk**
screen shot 2018-06-20 at 17 30 00
@kanitw @domoritz Should we call this vertical error band or horizontal error band?

It looks horizontal, but if we follow the error bar, this is vertical.

### CODE REVIEW

**Comment by domoritz** [comment]
Orient is vertical, right?

**Comment by chanwutk** [comment]
Yes, the Orient is vertical.

**Comment by chanwutk** [comment]
@domoritz I misunderstood your question. Error band does not add orient property to the area/line. The orient of the error band is to determine the axis that would be aggregated.

**Comment by kanitw** [comment]
> @domoritz I misunderstood your question. Error band does not add orient property to the area/line. The orient of the error band is to determine the axis that would be aggregated.

The question is what is the underlying (implicit) area orientation. You can test this by editing the `orient` in the normalized spec.  The right one shouldn't modify the plot.

**Pull request merged**
