### PR TITLE
Fix gallery flexbox in Safari and Chrome

### PR DESCRIPTION
**Pull request by willium**
Quick fix for #930. 

Tested in:
- [x] Safari Version 9.0.2 (11601.3.9)
- [x] Chrome Version 47.0.2526.111
- [x] Firefox 33.1.1
- [x] Firefox 43.0.4

### CODE REVIEW

**Comment by willium** [comment]
Looks like Trellis plots are broken. I'm not sure if that's because of my fix or they were broken before. I'll see if I can fix it.

screen shot 2016-01-15 at 5 06 58 pm

**Comment by domoritz** [comment]
It looks like some flexbox issue. Do you see the same issue in chrome 48?

**Comment by willium** [comment]
This is fixed in the latest, but will break as long as it's fixed height (based on current implementation). What happens if we do fixed height and a vertical trellis is too tall?

**Comment by domoritz** [comment]
> What happens if we do fixed height and a vertical trellis is too tall?

The content should scroll. 

odd

**Comment by domoritz** [comment]
It looks like we are not using the flex box alignment any more. 

screen shot 2016-01-15 at 21 10 59

**Comment by willium** [comment]
Fixed the trellis/max-height.

Re: alignment, which is desired:
screen shot 2016-01-17 at 2 13 28 pm

OR

screen shot 2016-01-17 at 2 14 26 pm

**Comment by domoritz** [comment]
I prefer the second option. Looks cleaner. Although I'm surprised that the heatmap is not aligned on top with the other charts.

**Comment by willium** [comment]
More like this then:
screen shot 2016-01-17 at 2 23 16 pm

**Comment by domoritz** [comment]
Almost ;-) I liked that the "View Source" and "Open in Vega Editor" are aligned at the bottom.

**Comment by kanitw** [comment]
LGTM and agree with aligned "view source" and "open in editor" if it's not
too hard.

**Comment by willium** [comment]
Great. I believe the latest works as desired. I also formatted the CSS because indentation was variable and it made it difficult to read.

**Comment by willium** [comment]
Also rebased because I figured it made more sense to only 1 commit for this in master

**Comment by domoritz** [comment]
Excellent. Works perfectly. I just changed scroll -> auto so that you only get the scrollbar when it's needed and switched to 2 spaces indentation. We use 2 spaces everywhere else so I wanted to make it consistent.

**Pull request merged**
