### PR TITLE
fix: document parallels, import projection type from Vega

### PR DESCRIPTION
**Pull request by domoritz**
Needs https://github.com/vega/vega/pull/2154

### CODE REVIEW

**Comment by domoritz** [comment]
@mattijn can you look at this and see whether it's right?

**Comment by mattijn** [comment]
I don't think I can test your branch in the vega-editor.

If you can test if the following Vega-lite spec renders without warnings on your development machine then I'm OK:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.0.0.json",
  "height": 480,
  "width": 640,
  "projection": {
    "rotate": [-20, 0],    
    "center": [0, 52.0],
    "parallels": [35, 65],
    "precision": 0.1,
    "scale": 700,
    "translate": [320, 240],
    "type": "conicConformal"
  },
  "layer": [
    {"data": {"sphere": true}, "mark": {"type": "geoshape", "fill": "none"}},
    {
      "data": {"graticule": {"step": [10, 10]}},
      "mark": {"type": "geoshape", "stroke": "gray", "strokeWidth": 0.5}
    },
    {
      "data": {
        "url": "https://vega.github.io/vega-datasets/data/world-110m.json",
        "format": {"feature": "countries", "type": "topojson"}
      },
      "mark": {"type": "geoshape", "fill": "lightgray", "stroke": "gray"}
    }
  ]  
}
```

Since this still gives some unwanted warnings in the online editor:

```
[Warning] Validation: should NOT have additional properties
[Warning] Validation: should NOT have additional properties
[Warning] Validation: /projection should NOT have additional properties
[Warning] Validation: should NOT have additional properties
[Warning] Validation: should NOT have additional properties
[Warning] Validation: should NOT have additional properties
[Warning] Validation: should NOT have additional properties
[Warning] Validation: should match some schema in anyOf
```

**Comment by domoritz** [comment]
Rotate needs to have three elements.

Screen Shot 2019-11-12 at 16 32 48

**Comment by mattijn** [comment]
Not sure where that comes from. In Vega the `rotate` accept a two or three-element array. As is mentioned in the [docs](https://vega.github.io/vega/docs/projections/#properties):

```
The projection’s three-axis rotation angles. The value must be a two- or three-element array of numbers [lambda, phi, gamma] specifying the rotation angles in degrees about each spherical axis. (These correspond to yaw, pitch and roll.) The default value is [0, 0, 0].
```

**Comment by mattijn** [comment]
Its on this [line](https://github.com/vega/vega-lite/pull/5542/files#diff-be64ac77866eb4f5448b9f10354e77d4R44) you changed:
```typescript
 rotate?: Vector3<number>;
```
How to write `Vector2<number>` OR `Vector3<number>` in typescript?

**Comment by mattijn** [comment]
I also don't see `parallels` in the `PROJECTION_PROPERTIES` [list](https://github.com/vega/vega-lite/blob/77b74291daf91a12a8b896f601c7a8dbd06af104/src/projection.ts#L83:L101)

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega/pull/2160.

**Comment by domoritz** [comment]
And #e5fd4514a

**Pull request merged**
