### PR TITLE
Add seattle weather example

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by jakevdp** [comment]
OK, I made the bar charts a multi selection that filters points in the top panel. Might take a few minutes to percolate through to the block.

**Comment by domoritz** [comment]
The default spacing in blocks isn't great. Can you make the upper chart smaller? 

screen shot 2018-03-08 at 11 51 49

**Comment by domoritz** [comment]
This would be a cool example for the weather tutorial. Right now, none of our tutorials use selections.

**Comment by jakevdp** [comment]
Made the upper chart smaller. Thanks!

**Pull request merged**
