### PR TITLE
Fix #4586: header smart align

### LINKED ISSUE #4586: Smart alignment based on angle for header
(We already do this for axis, but not for header.)

### PR DESCRIPTION
**Pull request by EvsChen**
Fix #4586

### CODE REVIEW

**Comment by domoritz** [comment]
Do you have an example? Can we make this simpler by not having cases for the different channels?

**Comment by kanitw** [comment]
I'm wondering if there is a general rule that we can use across header / axis  (and basically if we know orient and angle, we can do some math like rotating orient left by 90 degree to reuse the same logic for orient:top)

**Comment by domoritz** [comment]
I'm working on this in a separate branch.

**Comment by domoritz** [comment]
Replaced by https://github.com/vega/vega-lite/pull/4658

**Pull request closed without merging**
