### PR TITLE
Update applications.md -- PoleStar is now part of Voyager 

### PR DESCRIPTION
**Pull request by kanitw**
This might be a better version of https://github.com/vega/vega-lite/pull/3236

cc: @nyurik

### CODE REVIEW

**Comment by nyurik** [comment]
+1.  I also think that we should group all Vega-3 compliant tools in one section, vs the legacy ones that don't support it (yet).  thx!

**Comment by kanitw** [comment]
>  I also think that we should group all Vega-3 compliant tools in one section, vs the legacy ones that don't support it (yet). thx!

lol that's quite an amount of work and can get outdated very easily so I'd pass on this idea.

**Comment by nyurik** [comment]
@kanitw how do you mean?  Vega3 is fairly different from previous versions, so either a tool supports it, or it doesn't. I think we should have a section for the "current" tools, and everything else. Otherwise it misleads people into thinking there are all these projects even though the projects might no longer be maintained. I'm sure the community will help you with this list ;)

**Comment by kanitw** [comment]
Okie.  Feel free to submit another PR after we merge this PR.

**Pull request merged**
