### PR TITLE
Allow parsing inline data. Fixes #2143

### LINKED ISSUE #2143: Inline data requires a bogus URL to control parsing.
Say I have some inline data like this:

```json
[
  {"date": "20010101", "close": "1"},
  {"date": "20010102", "close": "2"},
  {"date": "20010103", "close": "3"}
]
```

This date format (`%Y%m%d`) doesn’t work with the default date parser, so I need to tell Vega the format. When the data is specified by URL, that works fine:

```json
{
  "data": {
    "url": "https://rawgit.com/mbostock/b556aa0f77b48505ea074469333125ae/raw/test.json",
    "format": {
      "parse": {
        "date": "date:'%Y%m%d'"
      }
    }
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "close",
      "type": "quantitative"
    }
  }
}
```
image

However if the data is specified inline, it appears the format.parse is ignored, so you get a blank chart:

```json
{
  "data": {
    "values": [
      {"date": "20010101", "close": "1"},
      {"date": "20010102", "close": "2"},
      {"date": "20010103", "close": "3"}
    ],
    "format": {
      "parse": {
        "date": "date:'%Y%m%d'"
      }
    }
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "close",
      "type": "quantitative"
    }
  }
}
```
image

Strangely enough, if you specify a data.url in addition to data.values, regardless of the value of data.url, it has the desired result of using your inline values and applying the format.parse. So the simplest workaround is to just put a blank `data:` URL in for data.url:

```json
{
  "data": {
    "url": "data:",
    "values": [
      {"date": "20010101", "close": "1"},
      {"date": "20010102", "close": "2"},
      {"date": "20010103", "close": "3"}
    ],
    "format": {
      "parse": {
        "date": "date:'%Y%m%d'"
      }
    }
  },
  "mark": "line",
  "encoding": {
    "x": {
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "close",
      "type": "quantitative"
    }
  }
}
```
image

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
Missing schema update

**Comment by domoritz** [comment]
Pushed schema update.

**Comment by kanitw** [comment]
@YuhanLu  Could you please update relevant docs?

**Comment by domoritz** [comment]
Doc update in https://github.com/vega/vega-lite/issues/2165

**Pull request merged**
