### PR TITLE
Better error messaging for unrecognized selection names.

### LINKED ISSUE #2635: Uncaught TypeError: Cannot read property 'getSelectionComponent' of null
screen shot 2017-07-06 at 10 27 22

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/europe_world_bank.csv"},
  "hconcat": [
    {
      "repeat": {
        "column": ["Population_ages_15_64_of_total", "Population_ages_65_and_above_of_total"]
      },
      "spec": {
        "mark": "bar",
        "height": 700,
        "selection": {"brush": {"type": "interval", "encodings": ["y"]}},
        "encoding": {
          "y": {
            "field": "Country",
            "type": "ordinal",
            "sort": {
              "op": "min",
              "field": "Population_ages_15_64_of_total",
              "order": "descending"
            }
          },
          "x": {
            "field": "Population_ages_15_64_of_total",
            "type": "quantitative"
          },
          "color": {
            "condition": {"selection": "!brush", "value": "steelblue"},
            "value": "goldenrod"
          }
        }
      }
    },
    {
      "mark": "point",
      "width": 260,
      "height": 260,
      "selection": {"brush": {"type": "interval"}},
      "encoding": {
        "y": {
          "field": "Population_ages_15_64_of_total",
          "type": "quantitative",
          "scale": {"zero": false}
        },
        "x": {
          "field": "Population_ages_65_and_above_of_total",
          "type": "quantitative",
          "scale": {"zero": false}
        },
        "color": {
          "condition": {"selection": "!brush", "value": "steelblue"},
          "value": "goldenrod"
        }
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by arvind**
Fixes #2635.

### CODE REVIEW

**Comment by domoritz** [comment]
Sweet. Can you add a test for it?

**Comment by arvind** [comment]
Done!

**Comment by domoritz** [comment]
Thanks! We use a different pattern for testing warnings in Vega-Lite. See https://github.com/vega/vega-lite/blob/master/test/fielddef.test.ts#L49 for example

```ts
it('should warn.', log.wrap((localLogger) => {
  foo();
  assert.equal(localLogger.warns[0], log.message.something(param));
}));
```

**Comment by arvind** [comment]
Gotcha. But this PR isn't actually issuing a warning (`log.warn`) but rather throwing an error (`throw new Error`). If an unknown selection is provided, compilation needs to abort. Throwing errors (rather than warnings) seems to happen across the compiler but I could only find one [explicit test](https://github.com/vega/vega-lite/blob/master/test/compile/compile.test.ts#L12) of it. 

How would you like me to proceed?

**Comment by domoritz** [comment]
How difficult would it be to completely ignore the selection and throw a warning instead? We try to be as forgiving as possible as resort to some reasonable alternative. However, in this particular case, I think it is okay to abort the compilation completely.

**Comment by arvind** [comment]
If we wanted compilation to proceed with invalid selection names, it'd involve non-trivial additional code paths to test for empty predicate expression strings (or partial strings in the case of logical composition) and then remove the containing part of the specification. This is because empty expression strings are invalid (and throw errors) in Vega.

For example, both of the following Vega snippets (which Vega-Lite could potentially generate for an invalid selection name) throw errors. Based on the additional necessary logic to remove `FilterNodes` and branches of production rules, my preference would be to just throw an error and abort compilation.

```json
"transform": [{"type": "filter", "expr": ""}]
```

```json
"update": {
          "x": [
            {
              "test": "data(\"brush_store\").length && data(\"brush_store\")[0].unit === \"\"",
              "signal": "brush_x[0]"
            },
            {"value": 0}
          ],
```

**Comment by domoritz** [comment]
Agreed. Thanks for the explanation.

**Pull request merged**
