### PR TITLE
Custom translate trigger for multiple intervals.

### LINKED ISSUE #2706: Can move wrong selection
In the example in the selection docs, I can move the brush that requires shift to be clicked when it is dragged out without pressing shift. 

editor

### PR DESCRIPTION
**Pull request by arvind**
This prevents the wrong selection from being translated (resolves #2706).

### CODE REVIEW

**Comment by kanitw** [comment]
Since @domoritz raises the issue, I'll let him review this then.

**Comment by domoritz** [comment]
Hmm, I can still move the red selection even though it should only work when shift is clicked. 

editor

**Comment by arvind** [comment]
Hmm, which example were you testing? I'm not able to reproduce this behavior with the three examples included in this PR (but perhaps I've forgotten to update other examples in the docs). For example, based on the GIF, I'm guessing it's `interval_mark_style.vl.json` but here's what I see with VL 2.0.0-beta.21 and VG 3.0.2:

brushshift

**Comment by domoritz** [comment]
I used the example from https://vega.github.io/vega-lite/docs/selection.html#interval-mark. I guess that one behaves correctly as we are not specifying the trigger to move the selection. 

I noticed another issue. When I create an overlapping red and grey brush and I want to move the grey brush, I can only move it if the brush is not being covered by the red brush. 

editor

**Comment by domoritz** [comment]
> We can open a feature request against vega-scenegraph, to address this in the future.

Thanks for the clarifications. I approved the PR. Please merge when we filed a feature request in vega-scenegraph.

**Comment by arvind** [comment]
Done: vega/vega-scenegraph#53.

**Pull request merged**
