### PR TITLE
Support `scale.bandSize` = `"fit"`, Top-level `width` and `height`

### LINKED ISSUE #194: Responsive Ordinal Scale (Ordinal Fit Mode)
Currently  `config.cell.width`, `config.cell.height`  are ignored for x and y if they ordinal scales respectively.  
Basically, the cell width and height of an ordinal scale is determined by the `band size * cardinality`.   

- [ ] ~~Let's add `config.unit.fitOrdinalScale` as boolean to make the ordinal scale rely on the `config.unit.width/height` value instead of bandWidth.~~  See below
- [ ] Need to deal make the scale work with all mark type.  
- [ ] corner case when the cardinality of the ordinal field is too high
- [ ] Of course, add tests.

### PR DESCRIPTION
**Pull request by kanitw**
Fix #194

### CODE REVIEW

**Comment by domoritz** [comment]
Nice!

**Comment by kanitw** [comment]
We also need to decide whether we want to allow `padding` when `bandSize` is a number and thus the underlying ordinal scale is a point ordinal scale.

**Comment by domoritz** [comment]
> We also need to decide whether we want to allow padding when bandSize is a number and thus the underlying ordinal scale is a point ordinal scale.

I'd say lat's reduce the attack surface unless we have a compelling example.

**Comment by kanitw** [comment]
Yeah. In any case, I think it is hard to reason about this because when I experiment with properties, there is still this bug https://github.com/vega/vega/issues/502.   Thus, something I see isn't the correct behavior.

**Comment by kanitw** [comment]
Before we commit to this syntax, another alternative to scale.bandWidth = `'fit'` is to use `points` property to determine whether the x/y ordinal scale is a point scale or band scale (band scale is when `points` = `false`), but I found that more confusing.

**Comment by kanitw** [comment]
- [ ] Test Docs
- [ ] Update docs to warn about high cardinality case

**Comment by domoritz** [comment]
@ellisonbg @jakevdp This is the fit feature we talked about today.

**Comment by kanitw** [comment]
@domoritz  I've just updated the docs and should be in good shape.  Please let me know if you have any comment.  

I still have to change `round` to `false` by default when scale is `"fit"` as unrounded scale is more scalable for higher cardinality.

**Comment by peller** [comment]
Looking forward to seeing this PR land.  However, I notice that the top-level width and height still relate to the plot area and not the overall chart with axes and labels.  The latter is what's needed for most apps doing layout.

**Comment by kanitw** [comment]
> However, I notice that the top-level width and height still relate to the plot area and not the overall chart with axes and labels. The latter is what's needed for most apps doing layout.

Vega 2 doesn't support this well yet anyway.  However, Vega 3 will have better support for this and we're planning to use Vega 3 for Vega-Lite 2.

**Comment by arvind** [comment]
> Vega 2 doesn't support this well yet anyway.

Vega support a `strict` padding option which lays out a visualization such that, after axes and legends have been added, the top-level `width` and `height` is respected.

**Comment by kanitw** [comment]
@arvind  Oh this seems new to me.  Good to know then.   That said, to support it in Vega-Lite would be a separate issue from this PR.

**Comment by peller** [comment]
Sorry, one more issue.  I tried using the [View Component API](https://github.com/vega/vega/wiki/Runtime#view-component-api) on the `kw/fit` branch to set width and height and it had no effect.  Is this a vega-lite bug?

**Comment by kanitw** [comment]
> Is this a vega-lite bug?

It's implemented in a different way, so size of inner components especially when faceted are set manually so yeah, you can't use it (yet).

**Pull request merged**
