### PR TITLE
ci: pretend we have a different vega version to get new images

### PR DESCRIPTION
**Pull request by domoritz**
Update all images. Addresses https://github.com/vega/vega-lite/pull/8810#issuecomment-1485836800

### CODE REVIEW

**Comment by jonmmease** [comment]
It looks like these new images have the same issues I discussed in https://github.com/vega/vega-lite/pull/8811#issue-1644045195.

**Comment by domoritz** [comment]
Hmm, we need to bisect to figure out what causes this regression. @kanitw do you have cycles to look at this?

**Comment by jonmmease** [comment]
Did a manual bisect and the regressions are all due to the update of `vega-functions` from 5.13.0 to 5.13.1 in 5cdcc4d8ced5e598e249805106fcad8b115737dd

**Comment by jonmmease** [comment]
Looks like vega-functions 5.13.1 corresponds to Vega [5.23.0](https://github.com/vega/vega/releases/tag/v5.23.0). The changelog for vega-functions there is:

---
**vega-functions**

 - Fix lassoAppend expression function XSS. (Thanks @arvind!)
 - Fix scale expression function XSS (Thanks @ajxchapman and @hydrosquall!)
 - Update rollup config.

---
What we're seeing looks like something gone awry with scaling, so I wonder if it's related to the scale expression XSS fix 🤔

**Comment by jonmmease** [comment]
@domoritz, these errors are now showing up in the Vega-Lite documentation. e.g. https://vega.github.io/vega-lite/examples/bar.html.

Screenshot 2023-04-17 at 7 57 45 AM

When I open in the Vega editor (which says it's using Vega-Lite 5.7 and Vega 5.24) the figure displays normally:
Screenshot 2023-04-17 at 7 58 29 AM

**Comment by domoritz** [comment]
We're looking at it in #8841

**Pull request closed without merging**
