### PR TITLE
Clean up model properties.

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
I'm confused, why are you moving these into Model? Should we just remove it from LayerModel?

**Comment by domoritz** [comment]
I'm not moving anything. They were defined in model before. We can remove them when only unit needs them.

**Comment by kanitw** [comment]
After we move facet to use the new layout, we'll basically have to revert half of this -- so let's say I'll take care of this later as this doesn't make my life easier.

**Comment by domoritz** [comment]
No, that's not true. You just cut and paste from model to unit. The previous state was worse because we had tons of copies.

**Pull request merged**
