### PR TITLE
Add Ask AI in README

### PR DESCRIPTION
**Pull request by royaljain**
## PR Description

Gen AI chatbot for vega-lite. Will help Developers understand this repository better. You can ask for code examples, installation guide, debugging help and much more.

<details>
  <summary><h2>Checklist</h2></summary>

- [ ] This PR is atomic (i.e., it fixes one issue at a time).
- [ ] The title is a concise [semantic commit message](https://www.conventionalcommits.org/) (e.g. "fix: correctly handle undefined properties").
- [ ] `yarn test` runs successfully
- For new features:
  - [ ] Has unit tests.
  - [ ] Has documentation under `site/docs/` + examples.

Tips:

- https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3 is a nice article about writing a nice PR.
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/).
</details>

### CODE REVIEW

**Comment by arvind** [comment]
Thank you for the PR. We're happy to hear suggestions (and receive PRs) on how to improve the repository, code examples, installation guide, debugging, etc. but will not be elevating a third party AI chatbot to the overall project README.

**Comment by domoritz** [comment]
@royaljain contacted me about his work and asked whether we would be willing to show the tool in our repo. I said that I'm hesitant until we get a demo and can let people evaluate it. So this wasn't unsolicited. I should have given the team a heads up that I encouraged experimentation.

I agree that we shouldn't promote a particular bot to the readme anytime soon. Nonetheless, this could be interesting as it's specifically optimized for Vega-Lite. I'm encouraging experiments and will give this a try from time to time. But until some more advanced users had the chance to vet the quality, it's not ready to be in the readme where beginners may pick it up and get misled.

An important question is of course why a specific bot is needed when a generic one could work with any repo via something like llm.txt (https://github.com/AnswerDotAI/llms-txt). I don't know.

**Comment by domoritz** [comment]
a bit of feedback. I played with it and asked a few basic questions that seemed to have reasonable answers. They were quite verbose and should be shorter, though. I'm also missing some explanation of what specific capabilities the model has and how it was adjusted for the Vega-Lite use case.

**Comment by royaljain** [comment]
Hi @domoritz 

-- how it was adjusted for the Vega-Lite use case

I created a RAG (Retrieval-Augmented Generation) using the docs, tutorials and usage folders in the repo. Have added prompts like "Vega-Lite provides a higher-level grammar for visual analysis that generates complete specifications. Users are Developers asking questions about the repo" to improve the response quality.

-- They were quite verbose and should be shorter, though

I can add these prompts to tune it further and add further resources like issues etc 

-- An important question is of course why a specific bot is needed when a generic one could work with any repo via something like llm.txt (https://github.com/AnswerDotAI/llms-txt)

The main difference would be due to RAG. If unfamiliar, this is a database which contains concise representation about the repo and helps improve the context and thus the answers given by AI.


Overall, I am happy to work on improving the bot / wait for others to try and vet it further. But if it's a more fundamental issue, let me know if I should drop it. 

Thanks.

**Comment by royaljain** [comment]
-- I can tell people on our slack about this tool and we will see what the reaction over time is.

Makes sense. Email would be great.

**Comment by domoritz** [comment]
Instead of adding this to the readme, I added it in a new section under AI tools: https://github.com/vega/vega-lite/pull/9491

**Pull request closed without merging**
