### PR TITLE
Refactor + Standardize Selection State Representation

### PR DESCRIPTION
**Pull request by arvind**
A major refactoring of how a selection state is stored within its dataset. This state uses tuples of the form:

```
{unit: string, fields: array<fielddef>, values: array<*>}.
```

where `fielddef` is an object of the form:

```
{field: string, channel: string, type: 'E' | 'R' | ... }
```
A `fielddef`'s `type` identifies whether the values being stored are simple enumerations (`E`) or represent ranges (`R`) of different kinds (e.g., a right-exclusive range would be `R-RE`). 

This new state requires corresponding new Vega expression functions (vega/vega-parser#89). Besides simplifying several code paths, it's also allowed us to much more easily add a top-level signal named (partially addressing #1830 with a much simpler strategy than I described here: https://github.com/vega/vega-lite/issues/1830#issuecomment-379000974).

I've marked this PR as WIP until I've had a chance to test the changes more thoroughly, but it's ready for high-level feedback. 

Note: While this PR does not introduce any breaking changes to the Vega-Lite language, it is tied to whatever Vega version vega/vega-parser#89 lands in. So, in that sense, it is a "breaking change" that might warrant us bumping the major version number of Vega-Lite.

### CODE REVIEW

**Comment by arvind** [comment]
*Siiiigh*, the issue with `intersect` failing tests was due to a stale local build of Vega. 😭 Those tests have been re-enabled and everything passes locally for me now.

**Comment by domoritz** [comment]
I added a blocked tag. We can remove it once the necessary changes land in Vega.

**Comment by domoritz** [comment]
I guess we are waiting for a Vega release before we merge this. Is there anything else left?

**Comment by domoritz** [comment]
@arvind @jheer This PR is blocked by a Vega release only, right?

**Comment by arvind** [comment]
Yes, I think so.

**Comment by arvind** [comment]
Hooray, with Vega 4.3 this PR now passes CI and is officially ready for review/merge @domoritz, @kanitw!

**Comment by domoritz** [comment]
Not sure why, buy a bunch of SVGs are gone in this PR.

**Comment by domoritz** [comment]
@arvind do you know what's up?

**Comment by arvind** [comment]
Huh, that's a great question. Looks like all of those deletions seem to have happened via the `[Travis]` commits? I'm not familiar with how those are run and, off the top of my head, nothing in my commits for this PR should cause example deletions so I'm as puzzled as you...

**Comment by arvind** [comment]
One thought: is it actually deletions or an error in generating the files? It looks like they're all 1 byte sized, and viewing them in the rich diff view produces an "file is invalid" error. So perhaps Travis is having difficulty producing the SVGs for some reason?

**Comment by arvind** [comment]
Wow, I'm really confused about what is going on. After the runtime tests execute, Travis seems to go [completely off the rails](https://travis-ci.org/vega/vega-lite/jobs/440766451#L1124) and no longer gets to the example generation stage. Hmm.

**Comment by arvind** [comment]
@domoritz Looks like the error with SVGs has gone away with the fixes to the Travis process. So this PR should now be actually ready for review.

**Comment by arvind** [comment]
Thanks for the LGTM and the code cleanup @domoritz. I squashed #4216 into this PR but do you feel strongly about squashing this PR into master? My preference would be to rebase it to preserve the granularity of code commits in what is a pretty major refactoring. It'll help (me, in particular) remember design decisions more easily. I worry that squashing it will produce a single, extremely complex commit and it will be hard to untangle all the various components that went into the refactoring.

**Comment by domoritz** [comment]
The advantage of squashing is that we can read the commits to write the changelog. Moreover, you get a reference to the PR in the commit message. If we need to look into what went into a commit, we can go to the PR, read the comments and also see the individual commits. This only works if you go to Github. We have squashed complex PRs in the past. For this PR, I'm also okay with merging if you use `--no-ff`. Go ahead with whichever you prefer. I approve the PR.

**Comment by arvind** [comment]
Thanks for describing the rationale. The alternate workflow you propose makes sense to me, so I'll go ahead and squash this PR.

**Pull request merged**
