### PR TITLE
Hyphenate paragraphs

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kanitw** [comment]
From discussion in https://css-tricks.com/almanac/properties/h/hyphenate/, looks like Chrome suck at this, so I'm against this.    

Our text column is pretty wide, I can't imagine a case where we will really benefit from this.

**Comment by domoritz** [comment]
Chrome 55 supports is now and firefox and safari supported this for a while. It makes text flow much nicer.

**Comment by domoritz** [comment]
Chrome 55 supports it and so do safari and Firefox. I just enabled it on my
website.

**Comment by willium** [comment]
I personally think we should not do this. Hyphen's really only belong in justified text IMO.

**Comment by kanitw** [comment]
I agree with @willium.
So 2:1 @domoritz.  lets close this?

**Pull request closed without merging**
