### PR TITLE
feat: set `resize: true` when axis orient signals are used

### PR DESCRIPTION
**Pull request by haldenl**

### CODE REVIEW

**Comment by kanitw** [comment]
Thanks for the PR.

However, all tests are failing.  Also, I'm not sure why this should be a part of `aria-2` branch?

**Comment by haldenl** [comment]
Yeah I need to fix all those. There are a few different errors... some look funny.

```
$ /home/runner/work/vega-lite/vega-lite/node_modules/.bin/jest test/
6
/home/runner/work/vega-lite/vega-lite/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
7
Error: Failed to launch the browser process!
```

I'll investigate.

I branched off aria-2 b/c the orient vega pr was off 5.11.0. Now that 5.11 is in vega I'll branch off t he VL 5.11? Branching off master would make it difficult to test due to mismatch of VL and Vega.

**Comment by kanitw** [comment]
LGTM, feel free to manually merge into ` hl/axis-orient`. 

There should be no conflict if you drop the auto update example commit.

**Comment by haldenl** [comment]
Manually merged into #6421

**Pull request closed without merging**
