### PR TITLE
Removed unnecessary imports from bin.test.ts

### PR DESCRIPTION
**Pull request by NeelMohapatra**
I thought tslint takes care of this

### CODE REVIEW

**Comment by kanitw** [comment]
Thanks!

**Comment by domoritz** [comment]
Thanks but don't spent time on this for other files. Once the linter works again it will do it for us.

**Comment by kanitw** [comment]
There was a bug in tslint so we had to hide this flag.

**Comment by NeelMohapatra** [comment]
Ah. I only checked the imports in this file because I wrote it myself.

**Pull request merged**
