### PR TITLE
Add search to docs overview.

### PR DESCRIPTION
**Pull request by domoritz**
CC @leibatt

### CODE REVIEW

**Comment by kanitw** [comment]
Screenshot?

**Comment by domoritz** [comment]
Forgot to make one and now I'm on mobile. It's a plain search input and a button next to it.

**Comment by kanitw** [comment]
This totally looks out  of nowhere. 

image

I agree that it's useful, but shouldn't the search box be on the menu bar instead? 

We can make room for it  by renaming Usage to "Using Vega-Lite" and move ecosystem to become another tab(s) inside "Using Vega-Lite".  The "Ecosystem" tab  is weird any way.

**Comment by domoritz** [comment]
> We can make room for it by renaming Usage to "Using Vega-Lite" and move ecosystem to become another tab(s) inside "Using Vega-Lite".

I'm worried that it makes the applications much less visible. I agree that it would be good to have the search more prominent but it's also not the best search since it just calls google (it's not well integrated into our page and it also only searches the docs right now).

I'd say this is better than nothing and we can iterate from here in follow up PRs.

**Comment by g3o2** [comment]
hmm, once you consider Search for documentation, I wonder whether you rather want a dedicated vl schema property search? i.e. search through keywords instead of a generic Google search ...

**Comment by domoritz** [comment]
> hmm, once you consider Search for documentation, I wonder whether you rather want a dedicated vl schema property search? i.e. search through keywords instead of a generic Google search ...

Yes, I think better search would be nice. I think we get some of that for free with https://github.com/vega/vega-lite/issues/4872. 

I'm merging this PR for now and we can iterate on it.

**Pull request merged**
