### PR TITLE
Use displayName for field title if it is specified

### PR DESCRIPTION
**Pull request by mprudhom**
Fixes https://github.com/vega/vega-lite/issues/571

### CODE REVIEW

**Comment by kanitw** [comment]
I'm not sure if `displayName` is the best property name, maybe we should consider other alternatives before sticking to this one. 

`title` or `fieldTitle` are also considerable options.    

@domoritz  thoughts?

**Comment by mprudhom** [comment]
My vote would be for "title".

**Comment by ZeningQu** [comment]
I'm using `fieldTitle` in the VL tooltip.

**Comment by domoritz** [comment]
Wait, we already have axis.title and legend.title. I think an explicit title property that can be used for both is a good idea.

**Comment by kanitw** [comment]
The only con of title is it is same name as the whole spec's title, which
is coming soon.

**Comment by domoritz** [comment]
> The only con of title is it is same name as the whole spec's title, which
is coming soon.

But it's in the channelDef/fieldDef and not the first level of the spec. I don't think that's an issue.

**Pull request closed without merging**
