### PR TITLE
Move mark-specific size scaleRange to mark specific config

### PR DESCRIPTION
**Pull request by kanitw**
See commits for details

### CODE REVIEW

**Comment by kanitw** [comment]
I'll add more test on the plane.   Let me know what you think about `opacities`

**Comment by kanitw** [comment]
Also let me know what you think about these properties names.  I just try to use full property name with min/max. (Size is usually a short for fontSize/strokeWidth/etc.)

**Comment by domoritz** [comment]
`config.mark.opacities` sounds odd. I think `opacityRange` is more intuitive.

**Comment by kanitw** [comment]
Okie, but we should still move it to config.mark right?

**Comment by domoritz** [comment]
I don't have strong opinions about that.

**Comment by kanitw** [comment]
@domoritz  Ok, I moved all scale range related stuff to mark and squashed that into the first commit.

**Comment by kanitw** [comment]
Note that the second commit is for related but different fix, so ideally shouldn't be squashed -- but not really a big deal.

**Pull request merged**
