### PR TITLE
Add Fremont Bridge bicycle count visualization

### PR DESCRIPTION
**Pull request by jakevdp**

### CODE REVIEW

**Comment by kanitw** [comment]
Another nice example :)  Thank you!

**Comment by domoritz** [comment]
I wonder whether it would make sense to ad some opacity or make the lines thinner.

**Comment by jakevdp** [comment]
@domoritz do you mean in the bottom panel in particular?

**Comment by domoritz** [comment]
Yes. The top one can be zoomed so it doesn't matter much.

**Pull request merged**
