### PR TITLE
Produced and dependent field fixes

### PR DESCRIPTION
**Pull request by domoritz**
See individual commits.

### CODE REVIEW

**Comment by domoritz** [comment]
@invokesus Do you think window and aggregates should have the group by fields in their produced fields?

**Comment by invokesus** [comment]
Having the same field in both `producedFields` and `dependentFields` is a bit confusing, no?

**Comment by domoritz** [comment]
I'm trying to think through what we use the dependent and produced field for. I think you're right. For example when we push a filter through aggregates, we should be able to do it. Okay, I'll revise.

**Comment by domoritz** [comment]
Rebased onto master

**Pull request merged**
