### PR TITLE
feat: support getBinStepSignal for prebinned data

### PR DESCRIPTION
**Pull request by domoritz**
Fixes https://github.com/vega/vega-lite/issues/6997

### CODE REVIEW

**Review by willium — APPROVED** [review]
Pretty elegant solution! A bit worried it may be brittle to use signals like this... are there other places this pattern is used?

**Comment by domoritz** [comment]
What do you mean by "this pattern"?

**Comment by jpkli** [comment]
This seems did not fix #6997. The encoding field for the point size may not have the _bin_ params, but the position and size of the points are still depended on the _x_ and _y_ encodings that are using pre-binned data, so this PR cannot handle such cases. 

I think we probably need to add additional cases in the [_sizeRangeMax function_](https://github.com/vega/vega-lite/blob/master/src/compile/scale/range.ts#L382) to handle this. When both fields for the _x_ and _y_ channels are using pre-binned data, we need to generate the signal for the point and circle sizes.

**Comment by domoritz** [comment]
Did you try it? I actually used your example and it worked.

**Comment by jpkli** [comment]
Actually, it works! I think I didn't set up my vega editor correctly when I tried earlier today. Now I can see it did fix #6997. Thank you very much!

**Review by jpkli — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
