### PR TITLE
fix: update deps and resolve issue with images in docs

### LINKED ISSUE #9151: Missing tooltip images in docs
At https://vega.github.io/vega-lite/docs/tooltip.html#tooltip-image the image doesn't show up. 

Screenshot 2023-10-23 at 11 47 04

### PR DESCRIPTION
**Pull request by domoritz**
Fixes #9151

### CODE REVIEW

**Review by keckelt — COMMENTED** [review]
The _issue with images in docs_ is resolved by the bumped vega-embed version ([6.24](https://github.com/vega/vega-embed/releases/tag/v6.24.0)) which contains the fix from https://github.com/vega/vega-embed/pull/1286

The [new vega-tooltip version (v0.34)](https://github.com/vega/vega-tooltip/releases/tag/v0.34.0) contains the baseUrl feature.

**Comment by domoritz** [comment]
Yes. Does this look good?

**Comment by keckelt** [comment]
I have removed the duplicates from package.json's `devDependencies` and ran `yarn` again.

**Comment by domoritz** [comment]
Thank you. Good catch that my merge was broken.

**Review by keckelt — APPROVED** [review]
Looks good to me :-)

**Pull request merged**
