### PR TITLE
docs: update candlestick example

### PR DESCRIPTION
**Pull request by eitanlees**
I updated the candlestick example to use `ohlc.json` from https://github.com/vega/vega-datasets/pull/120

One thing I wasn't sure how to do was to reference the data as 

```json
  "data": { "url": "data/ohlc.json"},
```

Instead I used the full url.

### CODE REVIEW

**Comment by domoritz** [comment]
No need to use the full url once we update Vega datasets.

**Comment by eitanlees** [comment]
Oh, I was confused because ` "data": { "url": "data/ohlc.json"} ` didn't work in the online editor.

**Comment by domoritz** [comment]
I haven’t updated the editor with Vega datasets yet. I will do it soon but we don’t need to wait with this pull request.

**Comment by eitanlees** [comment]
ok, well then this PR should be good to go!

**Comment by domoritz** [comment]
We need to also update Vega-datasets in this pr.

**Comment by eitanlees** [comment]
Somehow I always mess up when trying to contribute here. Sorry!

I am going to close this PR because it has been replaced by https://github.com/vega/vega-lite/pull/5678

**Comment by domoritz** [comment]
I worries. It was easy for me to fix. Thanks for your pull request.

**Pull request closed without merging**
