### PR TITLE
chore: upgrade deps and fix build

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by domoritz** [comment]
@jonmmease huh, any idea why I am getting these changes after your pull request? 

Screenshot 2023-03-27 at 12 53 36

**Comment by jonmmease** [comment]
Oof, no I don't see how those would be related 🤔

**Comment by domoritz** [comment]
So weird. I merged your pull request and the tests failed (https://github.com/vega/vega-lite/actions/runs/4533528744/jobs/7986462429) so I thought this would fix it. Maybe the other changes I made in this pull request caused it.

**Comment by domoritz** [comment]
Hmm, definitely coming from your branch. I will never the commit.

**Comment by jonmmease** [comment]
Huh, I can't reproduce it in the chart editor: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykSArJQBWENgDsQAGhBMkUANZkATmwbiAJmhAB3GHTjSQOJBo01xZNAJk6aG+mgDMABhcz4NMljQAmNzIQmACeADaG6FBwoaFGGkiYKKgA2qDiSAgRIBYaDEHKwQD6QWzKhgC+UmkZWWIMylGFLkb1sejxiQTqiDihbMGZ4pgAtPKqEBDDOXmYyjRwECJikjIAZqXImGigIThZohJGJsoQEaAdWRcg5ZUgs0jiEOvKCGipIKvzoVrtCYYyuyymBomXUdBa4joEDeIGCcCQyiMCAkjgAujIkNCUrD4S8UTBClcZHCEcihgSLoU4JoQKjKjtgnttEgyCo+Jh-iAVGocExgjCSXjyYS-kZTnMFrSZGw8DCIAxXuiPl8NFjkiAoGohlKQJi5QrCpr1Fs6VU7oysiCcAwOUZPtEfiB5QhDVqtjJuQxefzseL5tClQo4D6caT8SLbTJMvQ2I7iEhQgxOfHExEXPTzUz0EF5AojJ7vQLcWT6BHDEr7d9tM7XcaxaUtqhQJWfuq-ZKlaUNHBEdju9BqeZLLTbnrfQajUNiollO6nRO3VSaZ3VqtTo2NdSOYjynSlRAvOlQmrqpltGC5ymk9tbocUqA4KQhliQMi8og2KQWjgrugaBAABUvXCAAKAsQIASgggACAB+aDwJg1BoIva5TVPS1NBmApih7f1CnCMhByMK8InEBgYmlSR7xAR8txPJ01AaLJiHmHQjEBbQoFCGhFCRBEFHSM9szwhYCPIQdigGJg2GPa4zTqZjtFYuB2IBC0uJ4viowEoTalEiBxKIzQCKQJhomhDNFKiZS2I4jTIi0vMdOUQSamrAyjMkrcJUspUvV-EAOgVShSOggBCABeaDyJieDgoQUKEyTZCDAQSDWA5BAIGSFxUUyxAcryygEqS1M7VKGzUFmJMMzo583lAayWLs9Ssw1Jy0JkALRXQcL6swAqEGggAfEaIoSuCYoo0JoNSrD8iKdtDMI4i1kqiIargXcMz07RpkW79AuIUIAGVojgKBgQkAAlBZZNIECAB1sgW2YlswUo4BeqRoJesEJB+6Ctt+raIPkjD9renDMGAzkettP9oaWzzVs0CLIui2LZvg4AW3waCDvewpYd6OBCnx37SIJ5IiZw5avM0Ok5ummIIZAPakdyRaSbhimVWhGRSMazMsgAUTtFUPN8tDdvcrnsKKT7WXCEjkoiVYE1OKiRYGrFQEyZQiJF5rbNU+z2u43i8x27qf162in0GiB9FWTAAGlg1ls1Ode7nieRcxVn5HWaL17YnUPBMof9mG4fkkAEayQOaGD56-cV6cvqBumlbYFW4Cm7GWdz3myd+0vlbIcIi5mlmQcJ5GSfz6vC-gyu4ZZ7HwZ2pVkFchjfZMegCwtrJR7WVRXibD55DgRtIfQTWog5DRCmHglkAsOIEiSRj6kaZoPVUL0+TlAyR1ualNW7COk4juwHBgCOWwj0f0Efxwbg8OAvB8GfX4z3fhgX+3gtg3G-q+ASg95ZQIHmPZkZQUCBBCKrbECJ4Q6jELOF+UtfiwwQMkF6goSwUj+C9VECcLDbnkMCL81VlBJknmwae5xd7aGXvPOAa8N6FC3pIK+4gb5nETvbRGoBSjzG1DPYW6BSCzl4tHW4nw2Yz2gAmLImo+iIjWHgp0F9bwmCgHQH07wORBG0OFcIlh6AgQ6EgdOpcShlBelBUa40TrnXCFddg4gAILEwI4puzjvrSGgglcGQt1ZoAAIwZlkS4SgvhdwyH7FAOYOBrrUSalHNoIAXoXGgiBQUwxSEQWQi9aCABqIpwJMgADENgJDsQkBURDQxClLBcChv0ADkABSAAmr0txNSXoAG5oKnQVNBNgqxoKTkwBUkA1SinPE2C0gh7SayLJ6X9fJIBRn7MmctZZqyQL-gAGoJnsJstpL1loUJgvFVphCHkGQoSzF6L0qkJW2R82kPcZAAA8I7qLQSAUFuiHTaBIeGK4twfRNSgBo2FksYXZgXMaJcWhEW+DBSiiFIdlQYvnC6RZ04ETgNSXAT44huFgtyftCA1yeIaDuW8jppCyxPOggAMj5YTCA9SLAGBAr8157S4XCm6YC-lgqrk3PZX8h5WKhi8oFUKkVkIOTipVWS2s6rAXXAgXuQIhLJQ0V9lC0W2g6mcg0CwpA28Z72OrExQ+6KqzoGlV00UtxlAPGNikdwOSyBHm0J-Z+ttF6wgQegHi9KERxCdS6thiR3UH3JkfEl3w1QGopTmHBgQ1WYBxSOGQgbLARHeAecN0d0CeDAfJPKMhIRVRBiAAAXj2NgaAtpy2EhqWSpR40gC7BYaOqTU3ZKCuw7MHrs1esdMtesOCGG1UrUGkRXBECaL+GQUowR-BMBNUqJAwLLW1otdoG1kitzaBktgFh+Y5gaFOjen1r77D9sYXAAE1sADCbpGX1ryVEGgoQQJRoIAAFhcECoKM60Ca2PP+kAoQzIWRQ1rdDCIaBJFQ9rKBwKxbAo5NI9wr4LBkYo42KjwJFBYiI+hrtOQ4CgtQOmBSn7IVGHvdI2QbBn2vGPj+1ALGAOYAhYU4puJSn4kiUh-hOG0PrReAkbQQyOLW1OjQHtaAqOYfMqEepiYXa-qYRhrDoQADy8jMM4Es+hxjChgN1jUUyyIv8oMwfg4htjmgOOGZSRhiSmgGIqPAyOnRTppKyQAg5DUNAGiqykxC1dMhr6xhEcZ7DM9fYMzRmvPLckZDUJ7LQmg9DO33xnjKeQJiRbmI3CBKx1IyC2PsUE2OH1s6HJgmNIpud-m+U+Zq9jwK5kXORqN-0ezSqkRggAPmighpTsi4lmgSZQJwAgdq3AgPFuSBXYFFfC2vI7CAZJldejQnxNW-121-BIoxTWaIte0G16xnWYCbIcS9Jxn0XEDfccN2b7yxu0nlY3bsU3Vgzd63NhYC3XllSTCttbUE1blVQFt0AO29sHay0MGWp2h3neMmvHy-ojAVcDQ9zaT3REveVKogn0T0D3EeMcB9ECbh0iAA)

**Comment by jonmmease** [comment]
@domoritz, I think I have a partial idea of what's going on here.  If you checkout `master` (after you reverted my change, I'm on eccc1a4c3d1e0403301cbcf9e112f8a2fd6d39bd) and delete the `examples/compiled/interactive_legend.png` image before running `./scripts/build-examples.sh` then the generated image has the x-axis label shifted way to the left as above.

I think this is a regression that already existed, but it wasn't caught because the images are only regenerated when the generated vega spec changes:

https://github.com/vega/vega-lite/blob/eccc1a4c3d1e0403301cbcf9e112f8a2fd6d39bd/scripts/build-example.sh#L33-L36

My change introduced an expected change in the spec, so the images were regenerated.

I'm wondering if there might be a regression in Vega that happened since this image was laster generated.

**Comment by domoritz** [comment]
Thanks for digging into this. Can you make a new pull request with the changes Arvind suggested? We can merge that then.

**Pull request closed without merging**
