### PR TITLE
refactor: use view height and width instead of gridScale

### PR DESCRIPTION
**Pull request by domoritz**
Relevant issue: https://github.com/vega/vega-lite/issues/4226

### CODE REVIEW

**Comment by kanitw** [comment]
I think there was a reason why we added it. 

Maybe it's not true anymore, but given this massive diff, I'd rather not merge unless you are willing inspect all of these and make sure.

**Comment by kanitw** [comment]
There are definitely some broken ones:

image

**Comment by domoritz** [comment]
I'm looking into it.

**Comment by domoritz** [comment]
We added it to gridlines are spanning the whole width/height of the view.

**Comment by domoritz** [comment]
The examples now work correctly.

**Comment by kanitw** [comment]
Have you looked at all output? (esp. layer and multi-view?) 

I'm suspecting this could be wrong for layer and multi-views, so we should at least check *all* of them.

**Comment by domoritz** [comment]
Let's not do it for now.

**Pull request closed without merging**
