### PR TITLE
Wrap overflowing code

### PR DESCRIPTION
**Pull request by domoritz**
Before

screen shot 2018-11-26 at 14 50 20

After

screen shot 2018-11-26 at 14 50 14

### CODE REVIEW

**Comment by arvind** [comment]
Is this preferable to `overflow: auto` or `scroll`? I wonder if it'll get confusing if non-description lines of the spec every wrap?

**Comment by domoritz** [comment]
Updated

**Comment by domoritz** [comment]
Hmm, we actually use wrapping in our docs: https://vega.github.io/vega-lite/docs/flatten.html. The advantage of wrapping is that you never have to scroll horizontally (which many people can't do).

**Comment by domoritz** [comment]
I reverted to wrapping.

**Comment by domoritz** [comment]
@kanitw @arvind Is this good?

**Comment by kanitw** [comment]
wrapping is good.  :)

**Comment by domoritz** [comment]
@kanitw approve the pr / merge it then?

**Pull request merged**
