### PR TITLE
Basic support for title

### LINKED ISSUE #431: Support adding title to a plot
- [ ] ~~Need to add another text mark group to the top-level marks~~
- [ ] ~~The first step is to always add title to the bottom.~~  
- [ ] ~~Then we might add mode for adding title to the top (and thus offset the main mark group)~~

### PR DESCRIPTION
**Pull request by kanitw**
Part of #431

### CODE REVIEW

**Comment by kanitw** [comment]
Hmm -- need to apply a few tricks -- according to https://github.com/vega/vega/issues/960

**Comment by kanitw** [comment]
I think we can just wait for the fix in #960 and just merge this instead of inventing temporary hack.

One bug to fix is that width/height signal in this spec https://pastebin.com/NYJeSUgd should become child_width/child_height

**Comment by kanitw** [comment]
Since this is the correct implementation, let's just hide it from the schema until we fix a relevant bug in Vega then.

**Comment by domoritz** [comment]
Please add some tests so we cover the lines in the patch.

**Comment by kanitw** [comment]
Those lines are unnecessary as we have duplicate codes -- https://github.com/vega/vega-lite/issues/2780

**Pull request merged**
