### PR TITLE
fix: use LogicalOperands for more complete multi selection signal.

### LINKED ISSUE #5143: Revisit multi-selection storage format when there are multiple projected fields
Consider this [spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSA3WAbArgKYDOKYA2uBhMJAIJmSwCMkANFABpkBMAHB0gAhRgCNWAXzZVqtBqiY92XMgFZVgkQtFKpMjHMawlg7qgDMPTWMnTqNekdamyAFlfXtu-QF0qezABbWAAnAGsyWngATwAHQkZYgHsASwA7eEgAqEI0gGMk6HSAc0j9SAAPSMgAMxTCXGhGbkEY+MYAR3xYDJTEeBSsBOzMaOq6hqaFBla4hIU0pMD0vCy7DEgC3CSQ8frGxhFZ9oWlldw18qTY2Dy+sdR0e02ktKKB1+r4EkzHyEXfmhIMQGoQ8h80owQbgwZkJFIoDgCPMwAAGAB05gk+mxEGyLzSdVKj3x0NhKU+fzJ4K+c0YgXwuAGylq+2gpFQ5Ec1h88JAEiAA) which has 

- `x = X`
- `y = A`
- `color = B`

image

If I project the selection on `fields: ["A", "B"]` and select 3 points one by one -- `(a2, b1)`, `(a2, b2)`, `(a1,b2)`.  My intention is that the predicate is `(A === 'a2' && B === 'b1') || (A === 'a2' && B === 'b2') || (A==='a1' && B === 'b2')`.

To store this intent, the selection signal should store the 3 tuples in a long format as `{"A":["a2","a2","a1"],"B":["b1","b2", "b2"]}`.

However, the selection signal currently stores `{"A":["a2","a1"],"B":["b1","b2"]}`, which makes it impossible to replicate the selection in an external tool.

### PR DESCRIPTION
**Pull request by arvind**
Fixes #5143. For multi-selections, the top-level selection signal contains an additional property named `vlMulti` which uses a `LogicalOperand`-esque structure to enumerate the entries in the selection store (not, we do not do any de-duping to keep things performant and consistent with the fact that it's difficult to resolve intersecting multi-selections across multi-views as described above).

In single views:

Kapture 2019-08-14 at 10 14 48

In unioned repeated multi-views (entries just get appended to the `or` array, rather than nesting): 

Kapture 2019-08-14 at 10 25 51

In intersected repeated multi-views (an `and` appears at the top level with nested `or` for each selected view):

Kapture 2019-08-14 at 10 29 41

### CODE REVIEW

**Comment by arvind** [comment]
@kanitw: Gentle ping on this -- does this address what you were looking for in #5143? If so, I can wrap up this PR in the next few days.

**Comment by domoritz** [comment]
Can you share the example specs you used? 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "Select multiple points with the shift key.",
  "data": {"url": "data/cars.json"},
  "selection": {
    "paintbrush": {
      "type": "multi", "fields": ["Cylinders", "Year", "Name"]
    }
  },
  "mark": "point",
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {
      "condition": {"selection": "paintbrush", "field": "Origin", "type": "nominal"},
      "value": "gray"
    }
  }
}
```

I still see the old representation. 

Screen Shot 2019-11-04 at 13 57 20

What am I doing wrong?

**Comment by arvind** [comment]
Yes, this doesn't work yet because it requires a corresponding change to the `vlSelectionResolve` Vega expression function (and a Vega release that incorporates it). That's why this PR is still marked as a draft – before I submitted the Vega PR, I had wanted to double check that this is, in fact, the desired outcome.

**Comment by arvind** [comment]
In the interests of time, and since a Vega 5.8 release is almost ready, I'll assume this _is_ the outcome we want and send the Vega PR later today.

**Comment by domoritz** [comment]
Yes, what I see from the gifs looks good to me.

**Comment by arvind** [comment]
Great, this should work once vega/vega#2129 is merged and released.

**Pull request merged**
