### PR TITLE
fix!: change default projection to equalEarth

### LINKED ISSUE #5367: Change default projection type
Now that Vega includes the [equal earth projection](https://en.wikipedia.org/wiki/Equal_Earth_projection), could It be included in Vega-Lite as one of the built-in projection types?

VL4 might also be an opportunity to change the default projection type away from mercator as this is rarely the most appropriate for the kinds of mapping Vega-lite is used for. Personally, I'd argue that the identity projection makes most sense as the default as it is semantically closest to 'unprojected' when a projection type is not specified. But if that is not suitable, the equalEarth projection would be far superior as a default compared to the mercator.

### PR DESCRIPTION
**Pull request by domoritz**
fixes #5367

### CODE REVIEW

**Review by kanitw — APPROVED** [review]
`fix!` rather than `feat!`?

**Comment by domoritz** [comment]
Why is it a fix? I consider this an enhancement (therefore feat!).

**Review by willium — APPROVED** [review]
Looks good! Would be nice to add an example that lets you try different projections with a drop down (as is available in Vega)

**Comment by domoritz** [comment]
Something like this:

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "width": 500,
  "height": 300,
  "params": [
    {
      "name": "projection",
      "value": "equalEarth",
      "bind": {
        "input": "select",
        "options": [
          "albers",
          "albersUsa",
          "azimuthalEqualArea",
          "azimuthalEquidistant",
          "conicConformal",
          "conicEqualArea",
          "conicEquidistant",
          "equalEarth",
          "equirectangular",
          "gnomonic",
          "mercator",
          "naturalEarth1",
          "orthographic",
          "stereographic",
          "transverseMercator"
        ]
      }
    }
  ],
  "data": {
    "url": "data/world-110m.json",
    "format": {"type": "topojson", "feature": "countries"}
  },
  "projection": {"type": {"expr": "projection"}},
  "mark": {"type": "geoshape", "fill": "lightgray", "stroke": "gray"}
}
```

Unfortunately, expr doesn't work here yet.

**Pull request merged**
