### PR TITLE
Use vega-datasets

### PR DESCRIPTION
**Pull request by domoritz**
* use vega-dataset
* add formula transform

### CODE REVIEW

**Comment by domoritz** [comment]
Need to fix date parsing for years.

**Comment by domoritz** [comment]
Works

```json
{
  "marktype": "line",
  "encoding": {
    "x": {"name": "Year","type": "T","timeUnit": "year"},
    "y": {"name": "Miles_per_Gallon","type": "Q","aggregate": "median"}
  }
  "data": {"url": "data/cars.json"}
}
```

Doesn't work
```json
{
  "marktype": "line",
  "encoding": {
    "x": {"name": "Year","type": "T","timeUnit": "month"},
    "y": {"name": "Miles_per_Gallon","type": "Q","aggregate": "median"}
  }
  "data": {"url": "data/cars.json"}
}
```

**Comment by domoritz** [comment]
I decided to add formula transforms (https://github.com/vega/vega-lite/issues/451). So this should work

```json
{
  "data": {
    "formula": {
      "field": "year",
      "expr": "new Date(datum)"
    }
  },
  "marktype": "line",
  "encoding": {
    "x": {"name": "Year","type": "T","timeUnit": "month"},
    "y": {"name": "Miles_per_Gallon","type": "Q","aggregate": "median"}
  },
  "data": {"url": "data/cars.json"}
}
```

**Comment by jheer** [comment]
Somewhat orthogonal to the general issue of using formulas, but relevant here: if we specify the type as `"T"` shouldn't we be able to appropriately "cast" behind the scenes? Relying on the expression language to get date/time objects may not play well across different implementations of vega-lite parsers/renderers. Expression language support should be an "add-on", not required.

**Comment by domoritz** [comment]
Goo points. My take on this is that I want to get the examples working first. Automatically parsing dates for example seems to be a can of worms that I don't want to open yet. In js vl we could automatically add a sensible formula transform if the user specifies the type `T` but I don't think that there is a great default parsing that I would recommend for other programming languages (e.g. Python).

**Comment by domoritz** [comment]
I just noticed that we automatically add a formula transform for time already. See https://github.com/vega/vega-lite/blob/master/src/compiler/time.js#L35

**Comment by domoritz** [comment]
The problem is that we add a utcmonth transform for the example from above. 

```
{
          "type": "formula",
          "field": "month_Year",
          "expr": "utcmonth(datum.Year)"
        }
```

**Comment by arvind** [comment]
I have a question after seeing the above addition of formula transforms to vega-lite. What is the guiding principle for where data transformation operators live in a vega-lite specification? Looking through the schema, I count:

1. `formulas` that appear in the `data` property. 
2. `filter` is a top-level property. 
3. `aggregate`, `bin`, and `sort` are specified within the visual encoding channels. 

I ask because this has implications for how the specification of interaction techniques can augment/override data transformation properties.

**Comment by domoritz** [comment]
We moved `filter` into `data`. `formulas` will also be in `data`. 

`aggregate`, `bin`, and `sort` are specifies in the encDef (visual encoding channels) because they make less sense in the global context. I would like to have formula in the encDef as well but @jheer and @kanitw decided against it as mentioned in https://github.com/vega/vega-lite/issues/451.

**Comment by arvind** [comment]
Cool, that dichotomy makes sense to me. Formulas within the visual encoding channels would dramatically restrict the expressivity of interactions.

**Comment by domoritz** [comment]
I think I understand the reasoning now. One of the goals of vl is that it can be generated automatically and that it can be supported by other languages (e.g. python). If we have expressions in fields in the encDef, this would be much harder. If we keep it in the data, we can say that we only support formula transforms in js.

**Comment by domoritz** [comment]
Okay, there seems to be some funny business going on when I choose month that are not related to the changes in this pr (see blow). This is ready to be merged. 

@kanitw Let me know if you want a separate pr for 2fe16cc. 

screen shot 2015-10-12 at 17 09 20

**Comment by kanitw** [comment]
Why do we need 7zip.png?

**Comment by kanitw** [comment]
Oh i see, it's a part of vega-datasets.  Sorry!

**Comment by kanitw** [comment]
@domoritz  Actually, it would be great if we can separate 2fe16cc if not too difficult.  

We can first fix all examples in the gallery we can publish a working `0.8.1` release (and ignore the month example) for now -- while adding formula transform (with a solution for its stats) to future `0.8.x` branches.  

We can also discuss more about roadmap in person tomorrow.

**Comment by domoritz** [comment]
I think the formula transform is simple enough that we can release it with 0.8.1.

**Comment by domoritz** [comment]
@kanitw resolved conflicts

**Pull request merged**
