### PR TITLE
Prevent tooltip from accidentally grouping lines + Refactor Path grouping Field

### PR DESCRIPTION
**Pull request by kanitw**

### CODE REVIEW

**Comment by kanitw** [comment]
Example in #3220 is fixed:

image

**Comment by kanitw** [comment]
Actually, I start wondering if this is a good idea.  Basically, the way Vega currently works, one group of line always produce one actual mark (and thus can only have one tooltip. 

There are two options:

a) Make tooltip do not group lines (like this PR does), but throw warning that tooltip will use value from the first item in the line grouping. 

b) Make tooltip group line like before, but throw warning that line grouping is happening due to tooltip.

I still think a) is a better option as Vega might become smarter with line marks in the future. 

Any thoughts?

**Comment by domoritz** [comment]
Hmm, this is a tough one but I think you are right that a) is less surprising. I'd still throw a warning that we only use the first value. And fix the tests :-P

**Comment by kanitw** [comment]
I just make the test passed.  However, I now start wondering if the error should be thrown at the Vega level (instead of Vega-Lite) when the tooltip channel is used for line marks and there are multiple tooltip values for each line. 

cc: @jheer

**Comment by domoritz** [comment]
Approved. Merge if you feel that this is right.

**Pull request merged**
