### PR TITLE
Added a candlestick example

### LINKED ISSUE #2432: candlestick charts
Do you support or will you support [candlestick charts](https://en.wikipedia.org/wiki/Candlestick_chart)? Is this already in the roadmap? (Thx.)

### PR DESCRIPTION
**Pull request by yhoonkim**
Fix #2432.

### CODE REVIEW

**Comment by kanitw** [comment]
LGTM.  Let's merge when the test passes :)

**Comment by kanitw** [comment]
Actually, two more minor comments:

1) can we remove the number of data?  So it doesn't have too be too wide and the file size can be smaller.  I'd say 1/3-1/2 of this plot is sufficient. 
2) Since we copy data from protovis, maybe adding a `description` field to credit that this example uses data and is inspired from ...url.... ?

**Comment by yhoonkim** [comment]
Waiting for #2511 to be resolved.
The below is the spec I wanted to replace to.
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 320,
  "description":"A candlestick chart inspired from Protovis(http://mbostock.github.io/protovis/ex/candlestick.html)",
  "data": {
    "values": [
      {
        "date": "01-Jun-2009",
        "open": 28.7,
        "high": 30.05,
        "low": 28.45,
        "close": 30.04,
        "signal": "short",
        "ret": -4.89396411092985
      },
      {
        "date": "02-Jun-2009",
        "open": 30.04,
        "high": 30.13,
        "low": 28.3,
        "close": 29.63,
        "signal": "short",
        "ret": -0.322580645161295
      },
      {
        "date": "03-Jun-2009",
        "open": 29.62,
        "high": 31.79,
        "low": 29.62,
        "close": 31.02,
        "signal": "short",
        "ret": 3.68663594470045
      },
      {
        "date": "04-Jun-2009",
        "open": 31.02,
        "high": 31.02,
        "low": 29.92,
        "close": 30.18,
        "signal": "short",
        "ret": 4.51010886469673
      },
      {
        "date": "05-Jun-2009",
        "open": 29.39,
        "high": 30.81,
        "low": 28.85,
        "close": 29.62,
        "signal": "short",
        "ret": 6.08424336973478
      },
      {
        "date": "08-Jun-2009",
        "open": 30.84,
        "high": 31.82,
        "low": 26.41,
        "close": 29.77,
        "signal": "short",
        "ret": 1.2539184952978
      },
      {
        "date": "09-Jun-2009",
        "open": 29.77,
        "high": 29.77,
        "low": 27.79,
        "close": 28.27,
        "signal": "short",
        "ret": -5.02431118314424
      },
      {
        "date": "10-Jun-2009",
        "open": 26.9,
        "high": 29.74,
        "low": 26.9,
        "close": 28.46,
        "signal": "short",
        "ret": -5.46623794212217
      },
      {
        "date": "11-Jun-2009",
        "open": 27.36,
        "high": 28.11,
        "low": 26.81,
        "close": 28.11,
        "signal": "short",
        "ret": -8.3743842364532
      },
      {
        "date": "12-Jun-2009",
        "open": 28.08,
        "high": 28.5,
        "low": 27.73,
        "close": 28.15,
        "signal": "short",
        "ret": -5.52763819095477
      },
      {
        "date": "15-Jun-2009",
        "open": 29.7,
        "high": 31.09,
        "low": 29.64,
        "close": 30.81,
        "signal": "long",
        "ret": 3.4920634920635
      },
      {
        "date": "16-Jun-2009",
        "open": 30.81,
        "high": 32.75,
        "low": 30.07,
        "close": 32.68,
        "signal": "short",
        "ret": 0.155038759689914
      },
      {
        "date": "17-Jun-2009",
        "open": 31.19,
        "high": 32.77,
        "low": 30.64,
        "close": 31.54,
        "signal": "short",
        "ret": 5.82822085889571
      },
      {
        "date": "18-Jun-2009",
        "open": 31.54,
        "high": 31.54,
        "low": 29.6,
        "close": 30.03,
        "signal": "short",
        "ret": 8.17610062893082
      },
      {
        "date": "19-Jun-2009",
        "open": 29.16,
        "high": 29.32,
        "low": 27.56,
        "close": 27.99,
        "signal": "short",
        "ret": 8.59872611464968
      },
      {
        "date": "22-Jun-2009",
        "open": 30.4,
        "high": 32.05,
        "low": 30.3,
        "close": 31.17,
        "signal": "short",
        "ret": 15.4907975460123
      },
      {
        "date": "23-Jun-2009",
        "open": 31.3,
        "high": 31.54,
        "low": 27.83,
        "close": 30.58,
        "signal": "short",
        "ret": 11.7370892018779
      },
      {
        "date": "24-Jun-2009",
        "open": 30.58,
        "high": 30.58,
        "low": 28.79,
        "close": 29.05,
        "signal": "long",
        "ret": -10.4234527687296
      },
      {
        "date": "25-Jun-2009",
        "open": 29.45,
        "high": 29.56,
        "low": 26.3,
        "close": 26.36,
        "signal": "long",
        "ret": 0
      },
      {
        "date": "26-Jun-2009",
        "open": 27.09,
        "high": 27.22,
        "low": 25.76,
        "close": 25.93,
        "signal": "long",
        "ret": 0
      },
      {
        "date": "29-Jun-2009",
        "open": 25.93,
        "high": 27.18,
        "low": 25.29,
        "close": 25.35,
        "signal": "long",
        "ret": 5.26315789473684
      },
      {
        "date": "30-Jun-2009",
        "open": 25.36,
        "high": 27.38,
        "low": 25.02,
        "close": 26.35,
        "signal": "long",
        "ret": 6.73758865248228
      }
    ]
  },
  "transform": [
    {
      "calculate": "datum.open > datum.close",
      "as": "isIncrease"
    },
    {
      "calculate": "(datum.open + datum.close)/2",
      "as": "mid"
    }
  ],
  "layer": [
    {
      "mark": "rule",
      "encoding": {
        "y": {
          "field": "mid",
          "type": "quantitative",
          "aggregate": "mean",
          "scale": {"zero": false},
          "axis": {"title": ""}
        },
        "color": {"value": "fff"}
      }
    },
    {
      "mark": "rule",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal",
          "timeUnit": "yearmonthdate",
          "scale": {"domain": [{"month": 5, "date": 31, "year": 2009},{"month": 7, "date": 1, "year": 2009}]},          
          "axis": {
            "format": "%m/%d",
            "labelAngle": 0,
            "title": "Date in 2009"
          }
        },
        "y": {"field": "low","type": "quantitative"},
        "y2": {"field": "high","type": "quantitative"},
        "color": {
          "field": "isIncrease",
          "type": "nominal",
          "scale": {"range": ["#ae1325","#06982d"]},
          "legend": null
        }
      }
    },
    {
      "mark": "bar",
      "encoding": {
        "x": {
          "field": "date",
          "type": "temporal",
          "timeUnit": "yearmonthdate"
        },
        "y": {"field": "open","type": "quantitative"},
        "y2": {"field": "close","type": "quantitative"},
        "size": {"value": 5},
        "color": {
          "field": "isIncrease",
          "type": "nominal",
          "scale": {"range": ["#ae1325","#06982d"]},
          "legend": null
        }
      }
    }
  ]
}
```

**Comment by domoritz** [comment]
What is this blocked by?

**Comment by kanitw** [comment]
there is an issue related to domain, which is assigned to you I think

**Comment by domoritz** [comment]
Then please link it to the issue.

**Comment by domoritz** [comment]
Issue is #2511

**Comment by kanitw** [comment]
@yhoonkim   #2511 is fixed -- Do you wanna rebase and test this again?

**Comment by kanitw** [comment]
Ping @yhoonkim

**Comment by millette** [comment]
The [example](https://vega.github.io/editor/#/examples/vega-lite/layer_candlestick) doesn't seem to render any data, only the y axis.

**Comment by paintdog** [comment]
example
For me it looks quite fine. (Thx)

**Comment by millette** [comment]
Ok, it worked it Chromium Version 57.0.2987.98 Built on 8.7, running on Debian 8.9 (64-bit) but not with Firefox 55.0.3 (64 bits) on Jessie Debian GNU/Linux.

No errors in the js console.

**Pull request merged**
