### PR TITLE
Add examples to concat, make a pass over repeat docs, add resolve exa…

### PR DESCRIPTION
**Pull request by domoritz**
…mple.

### CODE REVIEW

**Comment by domoritz** [comment]
@kanitw @arvind anything else I should do here before we merge?

**Comment by kanitw** [comment]
The diff looks reasonable, but not sure if you have addressed all (or most of) comments in https://github.com/vega/vega-lite/issues/1245

**Comment by domoritz** [comment]
Fair, can we still merge and reopen @1245?

**Comment by kanitw** [comment]
It's not closed yet lol

**Pull request merged**
