### PR TITLE
[WIP] remove string literals constant

### PR DESCRIPTION
**Pull request by nung25649**
Again, I'm so sorry for deleting and changing the pull request. I just figured out my git history tree was too messed up, so I decided to restore everything and create my own branch to start working on this. 

I have several questions regarding git:
1) How should I update the master branch into my working branch so that I always get the latest official version? Is `git rebase -i` a better option than `git merge`?
2) Should I do `git rebase -i` to clean up all of my commits every time a new namespace is removed?

### CODE REVIEW

**Comment by kanitw** [comment]
Sure. 

1.  I think you should read about it here: https://www.atlassian.com/git/tutorials/merging-vs-rebasing.  I link to Atlassian's tutorial in the [skill list](https://docs.google.com/document/d/1FSt7RL-KXtvNTmRDo3Zgb18uuuATOy95KX4oAobKDR0/edit) and mention rebase and merge, but maybe it wasn't clear, so I update the git section with more links.  

Make sure you read them carefully esp. this part: 

> The article might not be clear that in a rebase workflow, you should not merge master into your branch, but rather rebase your branch to to the latest master (run `git rebase master` after pulling master).  Otherwise, when you try to rebase, you will have to resolve conflicts again. 

2.
 
> Should I do git rebase -i to clean up all of my commits every time a new namespace is removed?

As I mentioned earlier in the email, your commit should be atomic -- one commit per namespace removed.  So you only need to do interactive rebase to squash (re-group) commits if your commits aren't atomic.   

Tip: Use Source Tree or other UI so that you can add only lines you want to a commit instead of always using `git add .`

image

**Comment by kanitw** [comment]
@nung25649 – These look good.  Let us know when you are done with all namespaces you plan to remove.

**Comment by nung25649** [comment]
I haven't removed TimeUnit namespace yet. It seems like its namespace appear in a lot of test files, including outputs for assertion, for example, in `encode.test.ts`, the namespace `it('should return correct expression for the timeUnit: TimeUnit.MONTH', function() {`. So should I keep this namespace or remove and replace all of its reference in test files with the string literals?

**Comment by kanitw** [comment]
@nung25649 Let's keep it then.  Is TimeUnit the only one left?  If so, I'll merge this.  Congrats!

**Comment by nung25649** [comment]
I just removed `NiceTime` from `scale.ts`. So yes, that's everything. 

Thanks! I'll start working on another pull requests.

**Comment by domoritz** [comment]
Thanks. This looks great @nung25649!

**Pull request merged**
