### PR TITLE
Extract function to compute orientation

### PR DESCRIPTION
**Pull request by domoritz**
With tests. 

Also contained in #1304

### CODE REVIEW

**Comment by domoritz** [comment]
Much simpler now. @kanitw, ready to merge.

**Comment by kanitw** [comment]
I think having "range" takes precedence over being measure.  I'll revise the logic and add more tests to cover the cases I'm thinking about and will ping you.

**Comment by kanitw** [comment]
Instead of having flip logic, I just rewrite the rule so that it should be correct now.   Feel free to take a look.

**Comment by kanitw** [comment]
Merging as we should release things with correct behavior.  

@domoritz  feel free to send follow-up comments.

**Pull request merged**
