### PR TITLE
fix(#8338,#8126): make boxplot work with single value per group

### LINKED ISSUE #8126: Boxplots with many identical values or just one value are missing the median line
For datasets with many identical values, it is understandable that there is no box drawn for q1 and q3, but the median line at q2 should always be present. Currently only outliers are shown which is confusing since it gives the indication that the dataset only contains a few observations, rather than potentially many observations compressed at the same value.

image
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLQBOAEzG2hgIyHDADgDsmOgCMwdMBJsWArDGMwXbE6eAGwSKnIgGgoATgDWOk4QAB4ADgA2EOLcmFCQdCRIqCBJqvCYaXQ6aApppNrchACeKdrIIACOpApEcMrEaNqy8koKlJiElKp6Ckam5la2Ds6u7p4+fgFBFqEqyADa6DV1KBYynIe1radschfHyNe3INWXJ2d3V+-PR1enTy-3Qw3AC6siAA)

My expectation would be to see the chart like it is shown in seaborn:
image

### LINKED ISSUE #8338: Boxplot disappear when there is one value per group
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A", "b": 28}, {"a": "A", "b": 30}, {"a": "B", "b": 55}
    ]
  },
  "mark": "boxplot",
  "encoding": {
    "x": {"field": "a", "type": "nominal", "axis": {"labelAngle": 0}},
    "y": {"field": "b", "type": "quantitative"}
  }
}

```
image

Nothing shows up for B. 

This is similiar to https://github.com/vega/vega-lite/issues/3488, but is the same problem for boxplot.

### PR DESCRIPTION
**Pull request by kanitw**
Fixes #8338, fixes #8126

### CODE REVIEW

**Comment by kanitw** [comment]
It's working now!

image

**Comment by domoritz** [comment]
Nice. Should we close then?

**Comment by joelostblom** [comment]
I think @kanitw  meant it is working on this branch?

Btw, @kanitw would this also fix https://github.com/vega/vega-lite/issues/8126

**Comment by kanitw** [comment]
Yep, I think so, it should fix #8126 too.

**Comment by kanitw** [comment]
image

**Review by fandu-db — APPROVED** [review]
LGTM. Get it in!!!

**Comment by joelostblom** [comment]
This is great, thank you @kanitw !

**Pull request merged**
