### PR TITLE
docs: update wind example

### LINKED ISSUE #6231: Windmap image broken
Screen Shot 2020-03-31 at 23 33 38

### PR DESCRIPTION
**Pull request by domoritz**
towards #6231

### CODE REVIEW

**Comment by kanitw** [comment]
Convert to draft? since I still can't preview the SVGs and you say in https://github.com/vega/vega-lite/issues/6231#issuecomment-610682431 that this doesn't fix the problem.

**Comment by domoritz** [comment]
I fixed the data parsing. This still does not solve the image generation for some reason but it's an improvement nonetheless.

**Comment by domoritz** [comment]
I filed https://github.com/vega/vega/issues/2662 for the rendering issue.

**Comment by kanitw** [comment]
FWIW, I'm not convinced that we should project it since we don't show other maps elements anyway, so adding projection only adds complexity to this example.


If we do overlay this windmap on top of actual maps, then it makes more sense to project?

**Comment by jwoLondon** [comment]
I think projection is important at this scale because it is generally bad practice to perform a (lng,lat) -> (x,y) projection when geographic distance between neighbouring cells noticeably varies.

**Comment by kanitw** [comment]
Thanks @jwoLondon.  Ok let's merge this.

**Pull request merged**
