### PR TITLE
add opacity channel

### PR DESCRIPTION
**Pull request by YuhanLu**

### CODE REVIEW

**Comment by domoritz** [comment]
Can you add a test or at least an example to the test gallery that uses this feature?

**Comment by kanitw** [comment]
Missing defaultScaleRange for opacity

**Comment by kanitw** [comment]
- [ ] support stack with opacity (I guess stack should be `'none'` by default)

**Comment by YuhanLu** [comment]
Where should I put `defaultScaleRange`? Is it better to hard code it into common.ts or somewhere else  like a `const defaultScaleRange`?

**Comment by domoritz** [comment]
The default opacity range should go in https://github.com/vega/vega-lite/blob/master/src/scale.ts#L75

**Comment by YuhanLu** [comment]
Documentation and example are added, ready for review.

**Comment by kanitw** [comment]
Please let us know once you're done with solving conflicts.

**Comment by YuhanLu** [comment]
Sorry I can't fix the conflict. Other than that this is good for review.

**Comment by domoritz** [comment]
You have to make a new pr for this.

**Pull request merged**
