### PR TITLE
Add special axis config

### LINKED ISSUE #1935: Add targeted axis config
Vega has a special axis config in addition to the general `config.axis`.

> Additional property blocks can target more specific axis types based on the orientation ("axisX", "axisY", "axisLeft", "axisTop", etc.) or band scale type ("axisBand")

We should add these to our interface too.

### PR DESCRIPTION
**Pull request by YuhanLu**
Fix #1935 
- Add `axisX`, `axisY`, `axisLeft`, `axisRight`, `axisTop`, `axisBottom` and `axisBand` in config.

### CODE REVIEW

**Comment by kanitw** [comment]
- Add comment explaining each of them? 
- there is axisBand, I wonder if there is `axisPoint` and `axis<OtherScaleType>`?  (You can try to test with Vega and see.

**Comment by YuhanLu** [comment]
I have tried some others (axisPoint, axisLinear) and they don't work in vega

**Comment by kanitw** [comment]
@YuhanLu  rebase? :)

**Comment by kanitw** [comment]
Don't forget to update the changed output vg spec :)

**Pull request merged**
