### PR TITLE
Transpose splom example.

### PR DESCRIPTION
**Pull request by domoritz**
Before:

screen shot 2017-10-25 at 15 00 54

After:

screen shot 2017-10-25 at 15 00 58

### CODE REVIEW

**Comment by domoritz** [comment]
Duh, shouldn't have tried to push this before running to a talk. I'll fix it tonight. Thanks!

**Comment by domoritz** [comment]
I don't think the repeat definition is correct. I reversed row and column for x and y and now it's correct. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "repeat": {
    "row": ["Horsepower", "Acceleration", "Miles_per_Gallon"],
    "column": ["Miles_per_Gallon", "Acceleration", "Horsepower"]
  },
  "spec": {
    "selection": {
      "brush": {"type": "interval", "resolve": "global"}
    },
    "mark": "point",
    "encoding": {
      "x": {"field": {"repeat": "column"}, "type": "quantitative"},
      "y": {"field": {"repeat": "row"}, "type": "quantitative"},
      "color": {
        "condition": {
          "selection": "brush",
          "field": "Origin", "type": "nominal"
        },
        "value": "grey"
      }
    }
  }
}
```

**Comment by domoritz** [comment]
Pushed

**Comment by domoritz** [comment]
@arvind merge if you think it's right now.

**Comment by arvind** [comment]
Looks like there's a merge conflict with the compiled SVGs. Can you regenerate them, and then feel free to merge after.

**Pull request merged**
